### ISSUE TITLE
Unique reload sounds for weapons with shared audio.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#13]
### Description
Certain weapons share the same reload sound, despite their varying amounts of heft (or lack thereof). Prime example is that the SMG, Rifle, and Rocket Launcher sound exactly alike when reloaded.

For the SMG, try for something that would better-fit the UAC-9mm ammo type. The Rocket Launcher rotates the magazine once to ready the first rocket; I seem to recall an appropriate sound being used in the Black Edition fork, see if you can contact Blackmore about this.

**Comment by BLOODWOLF333** [comment]
I don't like any of the free sounds available on the couple of websites I visited.  This isn't broken and no one else has said anything about it so, leaving it alone for now.
