### ISSUE TITLE
Flashlight interferes with freeing captured Marines

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#131]
### Version
Development snapshot v0.2.2.

### Environment
Desktop (Linux x64).

### Port
Zandronum 3.0.1.

### Description
If the flashlight is on it makes it impossible to free captured Marines. This was observed on Purist mode with Ultimate Doom. Turning off the flashlight while next to them will free them, or, simply not having it on before pressing the "use" key will do the trick.

**Comment by BLOODWOLF333** [comment]
Was able to duplicate
