### ISSUE TITLE
Experiment prematurely triggered in E2M4

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#132]
### Version
Development snapshot v0.2.2.

### Environment
Desktop (Linux x64)

### Port
Zandronum 3.0.1.

### Description
In E2M4 (deimos lab) the hallway that introduces the Experiment is next to a room that traps the player in until they hit a switch on the other side. Near the area with the Armor bonuses and the Light Armor items it is possible to make one of the Experiments burst out of their blood container despite that enemy not being able to see the player.

I'm guessing the Experiment enemy have a radius trigger that immediately aggravates them into action once entered regardless of an unobstructed view or not.

**Comment by BLOODWOLF333** [comment]
Yeah I've noticed this behavior too i'll see what I can do.
