### ISSUE TITLE
Use cleaned-up Doomguy audio from Zero X. Diamond.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#14]
### Description
A few months ago, Zero X. Diamond made his original audio recordings available to all, stating that the version in BD itself was the result of poor audio mixing. The archive he provided is several long files' worth of multiple takes of his work. Perhaps this audio can be spliced into the Community Extension, while also restoring the Advanced Taunts and One-Liners that were otherwise made separate from the main PK3.

https://forum.zdoom.org/viewtopic.php?f=37&t=67778

**Comment by BLOODWOLF333** [comment]
I downloaded these, listened, and a compared them to what is already in BD and *shrugs* I think what we already have is fine and these wouldnt make much of a difference to be worth the effort.  Im not really interested in this.
