### ISSUE TITLE
Drop Weapon places weapon at 0,0,0

### ISSUE THREAD

**Issue by mrdavereid** [BLOODWOLF333/Brutal-Doom-Community-Expansion#154]
### Version
Stable 0.3.0

### Environment
PC

### Port
Zandronum

### Description
Using "drop weapon" button (default L) or console WeapDrop command should drop the current weapon in front of the player. Instead, the weapon drops at 0,0,0 coordinates.

This was working normally with bd21.0.4patch_0424.

**Comment by BLOODWOLF333** [comment]
Verified :( which this sucks because I finally got all the weapons to actually drop and be able to be picked up online when you or another player dies but, it has now caused this weird bug.
