### ISSUE TITLE
Add fix for monster scouter

### ISSUE THREAD

**Issue by mrdavereid** [BLOODWOLF333/Brutal-Doom-Community-Expansion#155]
### Description
BD SCOUTER.txt breaks in coop games when you look at a teammate (divide by zero). I think a fixed version is actually sitting in the ACS folder of brutalv21.pk3 (ScouterThing.txt). It would be nice if this fixed version could be added to the expansion.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/91006831-13ec4200-e5a0-11ea-8db9-03b41f93b064.png)
It looks like it still retrieves the other players health and everything it just doesnt print it to the screen so, I can simply add in the lines to print that info out.  The scouter.txt in the ACS folder is significantly different: (ACS folder on left, current scouter on right I believe)
![image](https://user-images.githubusercontent.com/16950832/91006937-5a41a100-e5a0-11ea-9f77-1a39e619868d.png)

**Comment by mrdavereid** [comment]
SCOUTER.txt has this:
`int pc = enemyhealth * 100 / enemyhealthmax;`

Where enemyhealthmax comes from this:
`enemyhealthmax = GetActorProperty(new_tid, APROP_SpawnHealth);	//max hp`

We get a divide by zero on teammates because this enemyhealthmax always comes back as 0, the default value.

---
I believe working versions of the monster scouter script avoid this by adding MF_COUNTKILL to PickActor, thereby ignoring any actor which doesn't contribute to completion percentage.
`PickActor(0, GetActorAngle(0), GetActorPitch(0), 2048.0, 0, MF_SOLID | MF_SHOOTABLE | MF_COUNTKILL | !MF_CORPSE, ML_BLOCKEVERYTHING | ML_BLOCKHITSCAN, PICKAF_RETURNTID);`

The safest fix here is probably to simply add those flags to SCOUTER.txt, which will leave the rest of the functionality the same.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/91112904-e78d0000-e649-11ea-822e-a716f34bad5a.png)
Fixed
