### ISSUE TITLE
Restore cut feature: Impaled Marines.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#16]
### Description
When BDv21 was still in the beta and Release Candidate phases, there would be occasional spawns of dying, impaled Marines who can be put out of their misery for a small supply drop. Someone has already done this, and is already included in Dox's personalized addon. A link is provided for reference.

https://www.moddb.com/mods/brutal-doom/addons/impaled-marines-restored-and-finished

**Comment by BLOODWOLF333** [comment]
Why did Mark cut this?

**Comment by Shockwave508** [comment]
Nobody knows for sure; the assets are still lying around in the main PK3, and all the linked addon does is restore this decoration, as well as make them explodable/burnable.

**Comment by BLOODWOLF333** [comment]
We already have the goodie barrels so, Im not sold on why we would want this back.  I dont miss this feature.

**Comment by BLOODWOLF333** [comment]
Maybe Mark will add this back in v22 but, if not then I'm not interested in putting in effort into this.
