### ISSUE TITLE
  Ammo pickup screen flash

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#161]
### Version
v0.3.0 stable

### Environment
windows PC

### Port
GZdoom

### Description
When you try to pick up ammo but can't because you carry max amount you get screen flash as  if you picked it up.

**Comment by BLOODWOLF333** [comment]
I'm seeing this issue with all the weapon pickups but not for ammo.  But, yeah this issue has been present for a long time I'll try to correct it finally.
