### ISSUE TITLE
weapons don't switch on pickup

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#165]
### Version
0.3.0

### Environment
PC

### Port
GZdoom

### Description
Weapons that don't switch on pickup: slot  1, slot 5 , slot 7, slot 8, slot 9.

**Comment by BLOODWOLF333** [comment]
those never will.  Slot 1 is weak weapons that you will never switch to and 5, 7, 8, 9 are explosive/can damage the player so will never auto-switch that is done on purpose.

**Comment by qqqbbb** [comment]
Then it should be an option so people don't get confused.

**Comment by BLOODWOLF333** [comment]
I'll remove the +WEAPON.NO_AUTO_SWITCH

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/91605385-02a38c80-e936-11ea-9347-90c1107bcb2a.png)
It still is never going to switch to an explosive weapon if you have at least a pistol out because of the weapon selection orders.  And that is correct behavior from vanilla so....*shrugs*
