### ISSUE TITLE
Fist alt attack damage with berserk 

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#166]
### Version
0.3.0

### Environment
PC

### Port
GZdoom

### Description
Fist alt attack with berserk deals  damage twice. It's 4 times stronger than left button attack.

**Comment by qqqbbb** [comment]
PowerLeftCross state also has double frame.

**Comment by qqqbbb** [comment]
The same thing in KickRight and KickLeft states.

**Comment by BLOODWOLF333** [comment]
Corrected in 8ed3ccc
