### ISSUE TITLE
DyingRevenant

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#184]
### Version
current

### Environment
PC

### Port
GZdoom, 

### Description
DyingRevenant stays forever in crawling pose. Intended?
You can destroy it only by gibbing it.

**Comment by BLOODWOLF333** [comment]
There is no DyingRevenant actor I don't know what you are talking about?
![image](https://user-images.githubusercontent.com/16950832/92048822-55be7a80-ed4e-11ea-8b79-af67bafa3952.png)
That?
![image](https://user-images.githubusercontent.com/16950832/92048908-75ee3980-ed4e-11ea-8c7d-5f7dfb70eabc.png)
Then yes.

**Comment by BLOODWOLF333** [comment]
Yes that is how Mark intended it
![image](https://user-images.githubusercontent.com/16950832/92049254-83f08a00-ed4f-11ea-93a5-4fb10a12f622.png)
