### ISSUE TITLE
Player can move during fatality

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#186]
### Version
current

### Environment
PC

### Port
 GZdoom

### Description
If you kill a monster with berserk combo you can move during fatality with WSAD keys.

**Comment by BLOODWOLF333** [comment]
Cant reproduce this.  Take all other mods off that may overwrite the Player.txt file and list what specific monsters your seeing this on because I tried it on all of them except bosses and I couldnt move.

**Comment by qqqbbb** [comment]
Not using any other mods. I can't reproduce it if I start fatality with a single LMB or RMB click but it happens almost every time if I strart fatality with RMB+LMB or LMB+RMB combo. It happens with any monster and only in current version, it never happened in v0.3.0.

**Comment by qqqbbb** [comment]
I can still reproduce this.

**Comment by BLOODWOLF333** [comment]
I figured it out, if you press primary fire during a fatality it lets you start moving.....wtf
