### ISSUE TITLE
empty energy cell casing

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#192]
I removed bright dots from empty energy cell casing sprites so they are easy to tell from ammo.
[SPRITES.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/5187467/SPRITES.zip)

**Comment by BLOODWOLF333** [comment]
I dont see why we would need this?  The ammo sprites are lit-up green and it's easy to tell between a casing and the ammo pickup.

**Comment by qqqbbb** [comment]
It's not easy. I thought empty cell sprite is a smaller version of ammo sprite until I placed them next to each other.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20200908_223307](https://user-images.githubusercontent.com/16950832/92551342-5e69f180-f223-11ea-81a1-b6ceb8deccd7.png)

*scratches head* I mean, that's easy to tell apart for me.  Im not sold on this.

**Comment by qqqbbb** [comment]
It's easy if you place them next to each other and you are not color blind.
