### ISSUE TITLE
Minigun

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#193]
Minigun spinning animation looks fine when you press alt fire. But when you fire it looks broken.

When you press fire button there is no start spinning sound.

Spin up time when you press fire buuton is too short so there is no reason to use alt fire.

 Alt fire. spinning sound keeps playing when you deselect minigun.

In Hold state there is line that plays useless sound:
CHAG A 0 A_PlaySound("MINIGEN", 5)
It should be replaced with:
CHAG A 0 A_StopSound(5)

I removed clicking sounds from beginning and end of spin down sound:
[CHAINSTO.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/5189150/CHAINSTO.zip)

**Comment by BLOODWOLF333** [comment]
> Minigun spinning animation looks fine when you press alt fire. But when you fire it looks broken.
I cant do anything about that those are the sprites Mark made for CHAFA - CHAFD no one else has had an issue with it and it doesnt bother me.
And there's nothing wrong about the clicking sounds for the minigun.  
https://youtu.be/1BPNEFyWeBs?t=237

**Comment by BLOODWOLF333** [comment]
This is going to be reverted too many people are complaining about the change and liked it the way it was.
