### ISSUE TITLE
gun fire sound volume

### ISSUE THREAD

**Issue by qqqbbb** [BLOODWOLF333/Brutal-Doom-Community-Expansion#195]
Some gun sounds are too loud. Here is code for  SNDINFO.BD to normalize them.

$volume weapons/rifle 0.6 // assualt rifle
$volume FARRIF 0.8 // far assualt rifle
$volume HMGFIRE 0.4 // machine gun	
$volume FARHMG 0.7 	// far machine gun 
$volume FARSHT 0.7  // far shotgun and pistol
$volume PFIRE 0.7   // pistol
$volume weapons/sg 0.7 // shotgun 
$volume weapons/sgpump 0.7 // shotgun pump
$volume UNMSTA 0.7 // unmaker
$volume UNMLOP 0.7 // unmaker
$volume UNMSTO 0.7 // unmaker
$volume A12FIR 0.8 // assault shotgun
$volume weapons/firegrenade 0.5 // grenade launcher
$volume SMGFIRE 0.7 // submachine gun
$volume SSHFIRE 0.5 // SSG
$volume PLSM9 0.9 // plasma
$volume PLSCHARG 0.7 // plasma
$volume PLSALTFR 0.9 // plasma alt fire
$volume BEPBEP 0.5 // plasma gun beep
$volume PLSDRAW 0.7 // plasma gun draw
$volume CHAINSPI 0.7 // 
$volume CHGNSHOT 0.7 // 
$volume FARMGN 0.8 // 
$volume CHAINSTO 0.9
$volume RAILR1 0.5 // railgun ready
$volume MP40 0.5

**Comment by BLOODWOLF333** [comment]
I agree that the unmaker is too loud but, everything else no one has ever voiced a problem with.  This is getting to be really knit-picky.

**Comment by BLOODWOLF333** [comment]
Set the Unmaker sounds to 0.7 and there is hardly any difference.  This will not be worked on.
