### ISSUE TITLE
Monster Dying States Are Not Consistently Solid or Not Solid

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#2]
Version: Dev Snapshot v0.0.1
Environment: Mobile (Delta Touch)
Port: LZDoom v3.85
Description: When killing zombie-class enemies with the Shotgun, certain death animations turn the fresh corpses into immovable barriers that players cannot pass through whilst the animation is still playing. Enemies affected include Pistol/Rifle Zombies and SMG/Shotgun Sergeants. Seems to happen whenever part of their torso is blown away, or if a hole is blown through their chest. Waiting until the corpse slumps onto the floor will rectify the issue, as well as continuing to blast them for some Cruelty Bonuses.

**Comment by BLOODWOLF333** [comment]
I don't think this is wrong behavior.  The monster technically hasnt "died" yet.  So, until it spawns the dead actor/corpse then yeah they should be solid because theyre still active and can be shot.

**Comment by Shockwave508** [comment]
Is there a way to make the Chaingunner's legs slump to the floor after a few seconds, if all other body parts are destroyed in his kneeling/dying state, but the remains are otherwise left alone? Otherwise, his legs will remain "upright" indefinitely, acting as a solid object unless destroyed completely.

**Comment by BLOODWOLF333** [comment]
After thinking about this at work today maybe all the dying actors should NOT be solid.  I can see them possibly being an annoyance and blocking the player in a slaughter wad getting him/her killed and I think the majority were -SOLID so Mark probably had a reason.

**Comment by BLOODWOLF333** [comment]
And the legs being solid objects shouldn't be possible they inherit from DeadChaingunguy1 which has the -SOLID flag.
