### ISSUE TITLE
Generic death message when player is decapitated by Imp.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#20]
### Version
Dev Snapshot v0.0.1

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
If an Imp manages to land a killing melee blow on the player's head hitbox, resulting in decapitation, a generic "Player died." message will display. Easily observed within the cramped maze of Ultimate Doom's E1M4.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/84558047-6c2bdb80-acf5-11ea-8409-95a8443d6869.png)

The Player doesnt spawn a head hitbox and takes 0.0 damage from "Head" damage.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/84558220-cc6f4d00-acf6-11ea-87ac-0eb398991650.png)

And the OB_IMPHIT and other obituaries are located in the sourceport so LZDoom must not have one by the name of "OB_IMPHIT".

**Comment by BLOODWOLF333** [comment]
Maybe I spoke too soon....asking the guys on the zandronum discord about this.
