### ISSUE TITLE
Cyberdemon in Ultimate Doom's E4M2 activation issue

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#212]
### Version
Development snapshot v0.4.1.

### Environment
Computer.

### Port
Zandronum.

### Description
In Ultimate Doom's map Perfect Hatred (E4M2) there is a platform that if stepped on in a specific area will trigger the Cyberdemon. In Brutal Doom this can be a problem because the Cyberdemon can get out of it's "cage" unlike other ports like Crispy Doom and start walking around on the uppermost platform and shoot at the player through the gaps in the ceiling. Below is a screenshot with the crosshair pointed near the area that can trigger it to start moving around.

![CybDemActivate](https://user-images.githubusercontent.com/22485442/94370460-bcb52200-00b5-11eb-9400-416284ca4222.png)

**Comment by BLOODWOLF333** [comment]
Yeah that was brought up before on the moddb page.  *shrugs* it makes it harder which fits the theme of the Brutal Doom but, I guess I'll set it's step height back to normal since this has been reported twice now.

**Comment by BLOODWOLF333** [comment]
Closed in b495c22
