### ISSUE TITLE
Option to force old style Spectre sprite for New Monsters

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#213]
### Description
Could you consider adding an option to force the Spectre sprite to use a shadow/fuzzy outline
like with the "old monsters" game option? Essentially, I just want this option so I can keep the brutal equivalents but without forcing the Spectre to be a pair of floating eyes.

Would go in "Brutal Doom Options">"BD Level Options".

**Comment by BLOODWOLF333** [comment]
Would have to create a 3rd Spectre actor (Spectro, VanillaSpectre, and this third one) because Mark made sprites for it that are literally just eyes.
