### ISSUE TITLE
Shotgun/SMG Sergeants are deaf, only detect via line-of-sight.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#22]
### Version
Dev Snapshot v0.0.1

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
Zombie Sergeants fail to detect the sound of a player's weapons fire, yet will spot them without fail if they enter their visual detection range. Observed in Ultimate Doom's E1M1, within the Green Armor room. Must play on Ultra-Violence to make them spawn.

**Comment by Shockwave508** [comment]
Not sure if this issue affects other enemies too.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/84559695-959f3400-ad02-11ea-847b-5f72b019b3f6.png)

Because they have the ambush flag set so they wait until the player moves into their line of sight.  They've been that way since 1994
