### ISSUE TITLE
Add square explosion decal workaround

### ISSUE THREAD

**Issue by Skibicki** [BLOODWOLF333/Brutal-Doom-Community-Expansion#221]
A GPU limitation can cause squares to appear in place of explosion decals. Link to workaround below
moddb.com/mods/brutal-doom/downloads/bdv21-patch-crater-explosion

**Comment by BLOODWOLF333** [comment]
Can you explain this more?  I dont understand how this fixes anything.  I tested with GZD 3.7.1 and am getting a normal/correct scorch decal at rocket impacts.

**Comment by Skibicki** [comment]
I'm sorry, I should have mentioned It's not my code. The Author is paladin-julio. I'm not sure how it works. The fix is for older hardware or possible driver limitations people with new hardware don't need this.

**Comment by BLOODWOLF333** [comment]
Ah, ok I messaged him.  Thanks

**Comment by BLOODWOLF333** [comment]
I'm not convinced we need this and judging by the number of downloads on the patch doesn't seem like many users have this issue to be worth trying to implement it.
