### ISSUE TITLE
Assault Rifle: Cannot use "hold ADS" properly in full-auto.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#223]
### Version
v21.5.1 (Development Build)

### Environment
Mobile (Android 10, Delta Touch)

### Port
GZDoom v4.5pre

### Description
When holding down Alt-Fire to zoom in with the Assault Rifle, the first bullet fired will disengage ADS immediately, and will continually swap between normal and ADS views, with every bullet fired in full-auto.

**Comment by BLOODWOLF333** [comment]
Yeah I just noticed that yesterday when looking into #222 I'm going to say this is part of the #222 fix
