### ISSUE TITLE
Dual-Wield Weapons: Instantly equipped when a duplicate weapon is picked up.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#225]
### Version
v21.5.1 (Development Build)

### Environment
Mobile (Android 10, Delta Touch)

### Port
GZDoom v4.5pre

### Description
In the case of dual-wieldable weapons, the Dual version of the weapon in question will instantly be equipped the moment your first duplicate weapon is picked up, potentially nullifying whatever heavy firepower you're slinging towards enemies. Might have something to do with the "Weapon.SelectionOrder" variable within the weapons' Decorate code being the exact same as their single-wielded counterparts.

**Comment by BLOODWOLF333** [comment]
This was specifically requested because dual wield weapons were never being auto equipped on pick-up previously
