### ISSUE TITLE
bug or feature//

### ISSUE THREAD

**Issue by nathanlycan** [BLOODWOLF333/Brutal-Doom-Community-Expansion#236]
### Version
stable version

### Environment
computer

### Port
gzdoom

### Description
i was in e2m7 and twice in the same spot an imp dropped a blue potion rather than a red cruelty bonus is that a bug or feature?

**Comment by BLOODWOLF333** [comment]
Feature.  I made Imps, demons, and lost souls have a rare chance of dropping a health bonus on death.  Every monster is able to drop something now very rarely.
