### ISSUE TITLE
Explosive Barrels: Timing of detonation is off.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#238]
### Version
v21.6.0 Development Snapshot

### Environment
Mobile (Delta Touch)

### Port
GZDoom v4.5pre

### Description
When shooting explosive barrels, anything and everything surrounding them are instantly damaged or destroyed, before the barrel itself even detonates. Something tells me that both the timing of the "exploding" animation and the timing of the explosion itself are the cause.

**Comment by BLOODWOLF333** [comment]
Yep i messed up the order of events, I thought I noticed something seemed off as well when testing online.
