### ISSUE TITLE
Friendly Marines continue to shoot after enemies die

### ISSUE THREAD

**Issue by Skibicki** [BLOODWOLF333/Brutal-Doom-Community-Expansion#239]
### Version
29938090088ae0e7ed980aadddb4f3405962bd29

### Environment
Desktop: Windows 8.1 64-Bit

### Port
GZDoom 4.5.0, LZDoom 3.87a, LZDoom 4.x

### Description
Shotgun and Super Shotgun Friendly Marines will briefly continue to shoot after an enemy dies. This was seen with the Baron of Hell and Mancubus. I did not see this with Zombie enemies or the Cyberdemon, but other combinations of friendlies and enemies are untested.

**Comment by BLOODWOLF333** [comment]
Yeah I've been noticing that too, that is kind of annoying.
