### ISSUE TITLE
Weapons With Ironsights: When toggled, ironsights are cancelled when Fire button is released.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#242]
### Version
v21.6.0 Dev Snapshot

### Environment
Mobile (Delta Touch)

### Port
GZDoom v4.5.0pre

### Description
When toggling ironsights with capable weapons, releasing the Fire button at any point will cancel ironsights immediately. I'm guessing there's a discrepancy with the toggle/hold code...

**Comment by BLOODWOLF333** [comment]
This was asked for on moddb by a kind of obnoxious dude but, If i get a second complaint about it I will revert it.

**Comment by aboutafter** [comment]
I thought it was a bug too. It's very annoying the way it is now and it makes me not use ironsights at all.

**Comment by BLOODWOLF333** [comment]
Alright then, if the player is firing in the ADS state and is not still holding altfire after the last shot then it will stay in ADS mode.  If they are holding altfire it will loop through the zoom end state and go back to the unzoomed ready once they release altfire.
