### ISSUE TITLE
Friendlies blocking item interaction

### ISSUE THREAD

**Issue by Skibicki** [BLOODWOLF333/Brutal-Doom-Community-Expansion#243]
### Version
a955e40ff8d96e56c70ebc1aecaeab157a2fd1a6

### Environment
Desktop: Windows 8.1 64-Bit

### Port
GZDoom and LZDoom

### Description
Friendlies should stay away from switches and other interactive items at least when the player is near them because they often cross the players path and block interaction with items.

**Comment by BLOODWOLF333** [comment]
Ummmmmmm I don't think it's possible to control that in simple Decorate or ACS they're pretty simple languages.

**Comment by Skibicki** [comment]
Is it possible to stop certain actors with a command?
As a workaround I use a keybind for the FREEZE command.

**Comment by BLOODWOLF333** [comment]
There is no possible way that I know of to trigger the Marine to A_Stop based off it's proximity to a switch or door or interactive item.  I'd rather keep this simple or I will never get this feature done.

**Comment by Skibicki** [comment]
Edit:  Sorry, I did not mean this as a complaint. I understand this would be complex and inefficient.
> Is it possible to stop certain actors with a command?

I will search around and edit this post with info and links If I find anything useful.

**Comment by BLOODWOLF333** [comment]
Will reopen if you find something.  I looked and didn't find a good way that would still be compatible with zandronum (which is the only port I play).
