### ISSUE TITLE
Standard Classes: Stamina "rises" when performing melee actions.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#245]
### Version
v21.0.6 Development Build

### Environment
Mobile (Delta Touch)

### Port
GZDoom v4.5.0pre

### Description
When performing any melee action with the Rifle Start and Pistol Start classes, a grey number appears at the bottom-center, that steadily rises with each swing. I can only assume that this is the Tactical Stamina working in "reverse", giving Stamina instead of taking it.

**Comment by BLOODWOLF333** [comment]
thats how stamina works in BD is it gives the inventory item and if over 50 will prevent the tactical doomer from sprinting.  And I added stamina to the melee attacks on purpose
