### ISSUE TITLE
Marines enter pain state if close to player's spawn point on map start.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#26]
### Version
Stable v0.1.0

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
When spawning into a new map, any Marines carried over from the previous level have a decent chance of entering a pain state if standing too close to the player's spawn point. Easily observed if the Marine in Ultimate Doom's E1M3 is saved, and he is alive when taking the secret exit to E1M9.

**Comment by BLOODWOLF333** [comment]
This would lead into the big mess of redoing the friendly marines feature so, putting this on hold.
