### ISSUE TITLE
Error when switching away from ammo dropper

### ISSUE THREAD

**Issue by neonvortex** [BLOODWOLF333/Brutal-Doom-Community-Expansion#264]
### Version
21.6.3 Development, 21.6.0 Stable

### Environment
Laptop running Windows 10

### Port
GZDoom 4.5.0

### Description
Pressing a key to switch from the ammo dropper to a weapon causes GZDoom to exit the map and go to the in-game console with the following message:

![image](https://user-images.githubusercontent.com/75443150/102222087-f75a7980-3eb0-11eb-89cf-9c0791dc8301.png)

**Comment by BLOODWOLF333** [comment]
This is the same issue we had with the meatshield weapons and GZDoom erroring-out because it doesnt know what player sprite to use I believe.  The end of the ammodroper deselect state had the Wait command and just need to change that to Stop to fix the crash.
