### ISSUE TITLE
Dual wield bug with "give all" command

### ISSUE THREAD

**Issue by neonvortex** [BLOODWOLF333/Brutal-Doom-Community-Expansion#265]
### Version
v21.6.3 Development

### Environment
Laptop running Windows 10

### Port
GZDoom.

### Description
The "give all" command (or the IDKFA/IDFA cheat) causes the player to equip dual wielded guns when they are selected, but switching back to the single weapon requires the player to pick up another weapon to dual wield again, as the player does not actually have the dual weapons.

**Comment by BLOODWOLF333** [comment]
Yeah I've been seeing that too I'll fix it.
