### ISSUE TITLE
Crash when performing an execution or any advanced animation such as rolling (GZDoom) & custom Full Helmet Hud does not properly fit screen after adjustment

### ISSUE THREAD

**Issue by SharpForceTrauma** [BLOODWOLF333/Brutal-Doom-Community-Expansion#266]
[CrashReport.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/5732889/CrashReport.zip)

Im using the latest 64 Bit version of GZDoom. For some reason the third person animations always crash out, especially demon executions.

Also, this is only a subtle problem, but the Full Helmet version of the hud isn't all the way in the bounds of the screen as depicted here:

![Screenshot_Doom_20201222_201740](https://user-images.githubusercontent.com/39568009/102951729-29f90900-4493-11eb-8f2c-a3fa3102f132.png)

My resolution is 1920x1080, and no matter how much i adjust the hud size or resolution or anything, all of the text won't fit on screen and it will be somewhat cut off at the top. Kinda annoying.

**Comment by BLOODWOLF333** [comment]
Go to Options>HUD Options>Scaling Options>and set Scale status bar to "adjust to fullscreen"

And I cannot duplicate the crashes when performing fatalities or rolls and taunts.  According to your Local.txt in the CrashReport zip your only using brutalv21.pk3 and not my brutalv21.x.x.pk3 expansion file so, that crash issue I believe I have already fixed in my Expansion.

**Comment by SharpForceTrauma** [comment]
Alright, can i get a link to that expansion then for me to try out?

**Comment by BLOODWOLF333** [comment]
I have the latest stable v21.6.0 on moddb on brutal doom's page under the files tab and here on Github you would click the code tab to the right of the issues tab and then on the righthand side of the screen click releases to see the stable and development releases and download the .pk3 file.
https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/releases/tag/v21.6.3

**Comment by BLOODWOLF333** [comment]
I'm assuming the issue has been resolved
