### ISSUE TITLE
Auto running bug when grab enemies holding pistol

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#269]
### Version
brutalv21.7.0

### Environment
 Desktop running Windows 10

### Port
GZDoom 4.5.0, Zandronum 3.0, LZDoom 3.87b

### Description

When grabbing enemies holding gun cause auto running moving mouse.

https://user-images.githubusercontent.com/76774186/103347289-3ab30b80-4a9f-11eb-8cdc-3fc29c57c982.mp4

**Comment by BLOODWOLF333** [comment]
Does this happen every time?  This was reported on the Brutal Doom Discord with Dox's addon and mine but, I cannot reproduce the issue.  With Zandronum 3.0 and GZDoom 3.7.1 but, what are the exact steps to make this happen and I might need to duplicate your mouse options or maybe the control scheme as well.

**Comment by BLOODWOLF333** [comment]
Are you playing Doom 2 Reloaded?  I've been informed that somehow that map wad causes this issue.  Idk why or how since I have yet to play it.

**Comment by Nic-Usor** [comment]
No. I actually playing The Community Chest Project.

**Comment by BLOODWOLF333** [comment]
The first one, cchest.wad?  And what level was that so I can pick it apart and try to figure this out?

**Comment by Nic-Usor** [comment]
Yes, the cchest.wad on map 06.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/103427090-05ccb480-4b84-11eb-94aa-f5b1c8cccb2a.png)
alright cant duplicate with Zandronum....

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20201231_162130](https://user-images.githubusercontent.com/16950832/103427112-45939c00-4b84-11eb-9369-789cf0ce14c2.png)
And that's GZDoom 3.7.1, i'll download 4.5.0 maybe Graf broke compatibility with brutal doom again.

**Comment by BLOODWOLF333** [comment]
GZDoom 4.5.0 I'm not able to duplicate either.  What are your Mouse settings and what is your keybind for grabbing enemies and then for Altfire to switch to the meatshield (holding pistol state)?

**Comment by Nic-Usor** [comment]
![Mouse settings](https://user-images.githubusercontent.com/76774186/103431418-1149cb00-4bd8-11eb-9607-ba5f3fc0104a.jpg)
![Mouse settings](https://user-images.githubusercontent.com/76774186/103431422-1d358d00-4bd8-11eb-81a9-205cee536222.jpg)
![Keyboard Settings 2](https://user-images.githubusercontent.com/76774186/103431423-1f97e700-4bd8-11eb-885b-56f58b71e9e4.jpg)

**Comment by BLOODWOLF333** [comment]
Does this happen every single time?  I'm still not able to duplicate the mouse moving the character.  Can you attach your GZD configuration settings file and I will try loading that up and if I then can duplicate the issues I can isolate if it's being caused by an option?
![image](https://user-images.githubusercontent.com/16950832/103432220-27886480-4ba1-11eb-8673-f3dad9cf7332.png)

**Comment by Nic-Usor** [comment]
Now I know how it caused the bug: when execute First Person Executions it causes auto running when grab enemies holding pistol .
https://vimeo.com/496181802

**Comment by BLOODWOLF333** [comment]
Thanks that was the clue I needed.  But, I still don't see how in the world it is possible that it is enabling mouse movement when equipping the meatshield weapons after performing a first person execution on a downed enemy.  That shouldnt be possible.
![image](https://user-images.githubusercontent.com/16950832/103447080-2eb87c80-4c4c-11eb-9363-c11f40b6ebf8.png)
I'll keep working on it.....

**Comment by BLOODWOLF333** [comment]
So the invisible MeatShield actor spawns had a velocity of 8 and I believe that was dragging the player forward constantly, once I removed that then the issue disappeared.
