### ISSUE TITLE
[suggestion] let sgt mark IV know about this

### ISSUE THREAD

**Issue by lofcz** [BLOODWOLF333/Brutal-Doom-Community-Expansion#274]
Sgt Mark IV is now planning to start dev of BDv22, it would be nice if he could work with this as a base. There is so much work done here and would be a shame to become obsolete with new version.

**Comment by BLOODWOLF333** [comment]
He knows, I'm on the Brutal Doom discord and have made sure I have permission to do this and all that.  Once v22 comes out I'm just going to have to go through and compare every file in Notepad++ and update the whole thing meticulously.

**Comment by lofcz** [comment]
> He knows, I'm on the Brutal Doom discord and have made sure I have permission to do this and all that. Once v22 comes out I'm just going to have to go through and compare every file in Notepad++ and update the whole thing meticulously.

That's great to hear I was non concerned about permissions, rather about possibility to merge these patches to v22
