### ISSUE TITLE
small request for BlOODWOLF333.

### ISSUE THREAD

**Issue by Matty4818** [BLOODWOLF333/Brutal-Doom-Community-Expansion#275]
Hey there, BLOODWOLF333. Forgive me for not being able to figure out how to personally message you, I'm not sure how to work the discord page to try and reach you, along with this website as well. I'm curious to know if you would be able to make me a .pk3 addon file for my older brutalv21.pk3 that I'm using. I tried to use your current version with my mods and I'm getting script errors and having problems with it, so I just continued with my own version. What I do enjoy about your current version is the slug rounds update for it. Is there any way you could send me just that upgrade in a PK3 file? That way I can put it in my folder and drag and drop it with my other mods? If so, that would be awesome! I was also having an issue with my version yesterday that I was hoping to get some insight into. I was running an older megawad with brutal doom v21 yesterday and when I grabbed a zombieman to use as a human shield, I began to throw him after his head exploded and the game stopped and the console screen came up. I hit escape and had to restart it but I was curious to what could have caused that crash because it happened twice on 2 different older megawads. Any info on that would be great and please let me know and if you're able to send me that slug rounds upgrade for my version of BDv21, if its not too much work for you. thank you so much. -matt

**Comment by BLOODWOLF333** [comment]
Yeah in GZDoom it VM aborts after running the pistol out of ammo and throwing the meatshield which is now fixed in v21.7.0rev1.pk3 which will be released on Feb 1.  And are you using my v21.7.0.pk3 "in-place" of brutalv21.pk3?  Alot of addons though my stuff may have broken compatibility with and they would have to be updated which they will end up needing when Mark releases v22.

[SlugRounds&MeatShields.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/5861631/SlugRounds.MeatShields.zip)

**Comment by Matty4818** [comment]
yeah I was using it in place of the old one, the zip file you sent isnt working brother. could you just send those 2 addons seperate as a pk3 so I can just drag and drop it with my other mods into my gzdoom exe? Its easier for me than trying to extract that one and adding it into the game. im sorry for being so difficult.

**Comment by BLOODWOLF333** [comment]
It's not that simple

**Comment by Matty4818** [comment]
How would I go about adding that zip file to my version? I’m sorry for the inconvenience I just want my version to work with it. I found a click and play version on YouTube a while back and I’ve been using it ever since with all my upgrades and wads with no problem. It’s using the gzdoom 4.2.4 version

**Comment by Matty4818** [comment]
Also, I figured out the problem with the script messages. When I add the BD_ScreenEffects.pk3, along with my other upgrades, that’s the only time the messages show up. It says Unknown Script 853 and Unknown Script 289. Hopefully that can be fixed. The screen effects work but seeing those messages when it starts is annoying. I’ve always liked the bullet holes in the screen, maybe in the upcoming release something can be added to turn it on/off.

**Comment by BLOODWOLF333** [comment]
Those addons are just not compatible with my mod.  All numbered scripts have been renamed to Named scripts so as not to conflict with any scripts in a map wad.  You would have to download Slade and read the manual and learn decorate and ACS and fix all the addons to work with your version.  I dont play with any other mods loaded and do not want the headache of trying to make everyone else's addons work with mine.  It's not worth the effort and is not a simple task.

**Comment by Matty4818** [comment]
No problem brother. Thank you for the advice, hopefully when V22 comes out all the stupid little bugs will be fixed.
