### ISSUE TITLE
Ultimate Doom E3M1 Pistol Start ammo a little unforgiving on Hard Realism?

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#277]
### Version
Stable 21.8.0.

### Environment
Computer.

### Port
Zandronum 3.0.1.

### Description
IDK if you play on the realism difficulties (I like Hard Realism myself) but I thought it would be worth bringing to your attention that the pistol start scenario can be rough if you don't like to use saves or play a certain way. The main problem is that the ammo drops in the starting section don't give you an additional ammo like the other modes do. Potentially leaving a big disparity in difficulty between Rifle start, Purist, and Tactical. I personally don't mind it myself and it's actually pretty fun. Just wanted to make sure this isn't an oversight.

**Comment by BLOODWOLF333** [comment]
>  The main problem is that the ammo drops in the starting section don't give you an additional ammo like the other modes do.
What do you mean?
But, yeah I don't ever play any of the non-standard difficulties and I do see that all the big ammo pickups are being replaced by the small picks up as defined in Mapinfo.txt I imagine that would be some bullshit to pistol start E3M1.
![image](https://user-images.githubusercontent.com/16950832/108273719-8f871000-7139-11eb-8489-2d7bccacb23f.png)

**Comment by KJeff01** [comment]
To clarify I meant that the player is going to be picking up Rifle ammo so the three ammo pickups in the starting area don't count for your pistol. Leaving the player with 16 rounds in their pistol and 30 ammo for the rest of the map.

**Comment by BLOODWOLF333** [comment]
I dont see any compromise with this thats how the map was made back in 1993 and changing all clipboxes to pistol ammo magazine drops would then screw over rifle start.

**Comment by KJeff01** [comment]
I'd think something could be conditionally set on a per mission basis by checking against the chosen game modes. Be it changing the drops or just giving the player a bit more ammo only for this mission. Judging with what you have to work with this isn't a likely possibility I suppose unless `replaceActor` could accept a conditional argument.

It doesn't matter much to me, I just think it's something odd with one of the game modes that affects this mission in a unique way.
