### ISSUE TITLE
Question about E3M2 platform

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#278]
### Version
Stable 21.8.0.

### Environment
Computer.

### Port
Zandronum 3.0.1.

### Description
Sometimes the platforms that house the shotgun guys don't lower since the pillar doesn't move. I'm unsure what is happening here unless the trigger is very specific. Just right now I can trigger it but only consistently by launching a rocket or grenade at one of the shotgun zombies from afar. Otherwise if your like I am in the screenshot you can't really do anything to make these platforms lower down.

![problemArea](https://user-images.githubusercontent.com/22485442/108259309-8e001c80-7126-11eb-9538-b9be29e773bd.png)

**Comment by BLOODWOLF333** [comment]
Yeah you have to shoot the red-back walls the shotgunners are standing in front of to make that pillar raise and then stand on the red triangle and they will lower.
![Screenshot_Doom_20210217_161035](https://user-images.githubusercontent.com/16950832/108274702-db868480-713a-11eb-9059-46da6332eccb.png)
![image](https://user-images.githubusercontent.com/16950832/108274748-efca8180-713a-11eb-9f26-70e66b14a7f0.png)

**Comment by KJeff01** [comment]
Damn that one stumped me good cause I'd be hitting the walls instead, not the back ones. Thanks for the info!
