### ISSUE TITLE
Scientist Zombie execution show Zombieman Sprite

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#284]
### Version
brutalv21.8.0

### Port
Zandronum

### Description
When make execution on Scientist Zombie it show Zombieman Sprite.

https://user-images.githubusercontent.com/76774186/109040017-2291ee00-76d6-11eb-9326-d103e12570c3.mp4

**Comment by BLOODWOLF333** [comment]
They aren't any sprites made for the labguy for that first person execution and I completely suck at trying to draw new things from scratch on the computer.  Somebody would have to create labguy sprites for this.
![Uploading image.png…]()

**Comment by BLOODWOLF333** [comment]
Implemented in https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/commit/1850fe4f7aafe97327d7b0ac5d891ef80213064b
