### ISSUE TITLE
Bugs and misbehaviors for NPC Marines told to hold position

### ISSUE THREAD

**Issue by starslab** [BLOODWOLF333/Brutal-Doom-Community-Expansion#286]
v21.8.0, running DOOM2 [I originally noticed on Extermination Day, and I've seen this sporadically on pre-Github v21]

Running gzdoom 4.5.0 on win10-64.

Rescue a few marine buddies and keep them alive. When you 'use' them to get them to hold position, they'll kinda go berserk after seeing and losing sight of an enemy. They'll either shoot at you [harmlessly], or if you have a group they'll all start shooting at each other.

They'll even do this when there are enemies they should be shooting at.

Possibly related, something's misfiring with their hitpoints. If one is injured, say he's showing 100/185 when you aim at him, when you tell him to hold position you will no longer see any hitpoint counter when aiming at him. If you then tell him to follow, you will see his HP again and now it will be full HP.

**Comment by BLOODWOLF333** [comment]
So when you press use on a marine and tell him to hold position or follow that is actually killing that marine and then spawning the following or guarding variant of that marine so, is why he goes back to full health.  That's how Mark has always had these marines and in effect allows the player to heal them sorta so I don't mind it and want to leave it as is.  The guarding marine behavior I will have to test out later today when I'm able to.

**Comment by starslab** [comment]
As far as healing, perhaps it might work better if "guarding" marines slowly regenerate health? Something on the order of 1 HP every couple of seconds? Just a thought.

Would be a more consistent experience if the mouseover HP view was always there, and didn't just magically "jump" back to full health for no obvious reason.

But yeah I mostly care about the AI misbehaviour, because that can really impact the game when you have a group of marines all being useless at each other.

**Comment by BLOODWOLF333** [comment]
Well, all the marines already are healing 1HP every 32 tics while in the Wait states for the following variant of the marines
![image](https://user-images.githubusercontent.com/16950832/109725905-7178d100-7b77-11eb-9a88-04be0a708269.png)
