### ISSUE TITLE
massive fps drop when you come close to the wall in blood

### ISSUE THREAD

**Issue by JIuBeP** [BLOODWOLF333/Brutal-Doom-Community-Expansion#287]
gzdoom 4.6 pre 
win 7 x64 ryzen 2600 gtx 950 ram 8gb
sometimes (in some cases) there is a massive fps drop when you come close to the wall in blood
video: https://www.youtube.com/watch?v=hyhDv0EIlnk

**Comment by JIuBeP** [comment]
trying change render mode, same problem/
i also check on more old version gz 4.2.1 and I did not meet such a problem (I saw less gory details there), hmm

**Comment by BLOODWOLF333** [comment]
Mark has said that he's fixed this in v22 whenever it comes out.  I'll ask what he did and if it's something I can add into mine now.

**Comment by BLOODWOLF333** [comment]
Hey, duplicate this issue again but shut your flashlight off and see what your FPS does.  I think the problem is the flashlight and not the blood decals.

**Comment by JIuBeP** [comment]
hmm, ok! im trying again/

**Comment by BLOODWOLF333** [comment]
Ok, the blood decals I've asked around and am waiting to hear back on what can be done/has been done to fix that but, the flashlight cannot be fixed.  It fires 3 invisible projectiles with different sized dynamic lights attached to each to give the appearance of a real flashlight.  The center small light-circle is full bright, 2nd larger light-circle is 2/3 as bright and then the 3rd largest light-circle is 1/3 as bright to give a gradient light effect for the flashlight.  If it just fired a single invisible projectile with a big full-bright light attached to it you would see a hard-contrasted edge and it would look bad.  So, I dont want to change it.  I've played with it a little bit yesterday and I don't see a better way to do it without it looking like ass.

**Comment by BLOODWOLF333** [comment]
Finally got some responses to this question from the zandronum devs and there's really nothing that can be done in a mod to address how inefficiently the port(zand or GZDoom) draws decals on walls.  So, I cant really fix this.  Most that can be done is simply set your max wall decals in the options menu to the lowest value so it will clean them up if their number gets too high.
