### ISSUE TITLE
NPC Minigun-Marine Guarding bug

### ISSUE THREAD

**Issue by starslab** [BLOODWOLF333/Brutal-Doom-Community-Expansion#289]
GZDoom 4.5.0, Brutal Doom -master, so effectively v21.9.0-pre

Guarding NPC marines now behave themselves since the previous fix, thank you very much.

The Minigun marine occasionally decides that he's bored and he doesn't want to be on guard duty anymore, and will change himself to follower-mode. I haven't been able to figure out how to reproduce this, he'll just sometimes decide that he wants to be near the player and gets himself killed, even though you left him (Several times!) guarding with a group of buddies.

I thought it was either when the player gets too far away (But sometimes I can be far away and he's fine) or after he finishes killing something (But sometimes he kills stuff and doesn't decide he's tired of life).

**Comment by BLOODWOLF333** [comment]
This has been reported previously and has been fixed so, it will be resolved in v21.9.0 https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/commit/38f4ca0d48bbbebaa2f2184bf07356fb55801933
