### ISSUE TITLE
Assault Shotgun fails to spawn spent magazine when reloaded.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#29]
### Version
Stable v0.1.0

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
When reloading the Assault Shotgun, spent magazines fail to spawn. Conversely, all other mag-fed weapons still spawn empty magazines as normal.

**Comment by BLOODWOLF333** [comment]
It has never spawned a mag/drum in standard brutal doom.  There is no code telling it to, Mark just never made that for this.
