### ISSUE TITLE
[Suggestion] Translation support branch for gzdoom

### ISSUE THREAD

**Issue by Blueberryy** [BLOODWOLF333/Brutal-Doom-Community-Expansion#290]
### Description
Make a separate branch of bdce but with translations support for gzdoom.

**Comment by BLOODWOLF333** [comment]
Translations support?  Honestly I don't like GZDoom and all the things Graff has changed/broken all I play is Zandronum.  So, I don't really have any desire to do this for something I will never use.

**Comment by BLOODWOLF333** [comment]
Looked into this and the TRNSLATE lump like that Dox added to his addon for the marines errors-out in Zandronum and I wish to maintain Zand compatibility so I will not be adding this.

**Comment by Blueberryy** [comment]
> Looked into this and the TRNSLATE lump like that Dox added to his addon for the marines errors-out in Zandronum and I wish to maintain Zand compatibility so I will not be adding this.

Alright. 👍
