### ISSUE TITLE
iconofsin.txt:400 #1 arg should be int

### ISSUE THREAD

**Issue by Kokokokoka** [BLOODWOLF333/Brutal-Doom-Community-Expansion#291]
### Version
master

### Environment
linux

### Port
k8vavoom

### Description
Error: /home/id0/doom/Brutal-Doom-Community-Expansion:iconofsin.txt:400:1: shit! `A_ExecActionSpecial` argument #1 should be `int`! (trying constant `BDBossHealth`)
Error: /home/id0/doom/Brutal-Doom-Community-Expansion:iconofsin.txt:400:1: Illegal expression identifier `BDBossHealth`
This is the only issue so far. commenting this line out helped me playing BDCE with k8vavoom

In zdoom derivatives the first arg is not checked on validity and is usually being set as 0 
proof:
https://zdoom.org/wiki/ACS_ExecuteAlways
for strings one should use:
https://zdoom.org/wiki/ACS_NamedExecuteAlways

**Comment by BLOODWOLF333** [comment]
This causes no problems in Zandronum or GZDoom what is wrong with k8vavoom?
