### ISSUE TITLE
Yet another crash when executing enemy.

### ISSUE THREAD

**Issue by SharpForceTrauma** [BLOODWOLF333/Brutal-Doom-Community-Expansion#294]
This is on the latest version. Same crash as last time I submitted an issue. Go to execute enemy, then the game instantly crashes to desktop and gives a crash report prompt.

I asked for help with this before. It was suggested I get the latest release.

I have few ideas as to what it could be. I have a top-spec machine to play this on, so I don't think it's a hardware issue. I doubt the WAD would have anything to do with it, and either way it's an authentic WAD ripped straight from an actual copy of Doom 2, so, probably what you would want the most.

The error report mentions something about trying to read a specific address. I don't know what that means.
[CrashReport.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/6213936/CrashReport.zip)

Please help. This is a good mod and half the fun is in the execution animations.
(FYI, i have "another" mod that uses a similar concept of an execution animation and it works just fine. This is the only one I seem to have trouble with.)

**Comment by BLOODWOLF333** [comment]
What specifically did you do?  You did a first person execution on a downed enemy or a fatality?  All your logs tell me is you were on Map05 of Doom2 and using GZDoom.

**Comment by BLOODWOLF333** [comment]
Ok I tried to duplicate this on Doom2 Map05 with v21.9.0 on GZDoom 4.5.0 and never experienced a crash doing first-person executions, fatalities, or stealth kills on imps through the doors (which the stealth kills going through doors bug is fixed recently).  So, is your GZDoom installed in ProgramFiles(x86) where permissions to read and write are denied by Windows?  If so try installing GZDoom to your desktop instead or just right click the GZDoom folder and enable full permissions for users/admin might be your issue.

**Comment by SharpForceTrauma** [comment]
I believe it's installed onto desktop, But I could check.
Also what initiated the crash was in fact a stealth kill through a door
(apparently that fix didnt hold)

**Comment by SharpForceTrauma** [comment]
Oh dear lord.

Disabling "read only" on the folder appears to have fixed it. I reloaded my
save and executed all the enemies several times and it still goes fine.

Never would have thought that had you not mentioned read and write
permissions XD

**Comment by SharpForceTrauma** [comment]
nevermind 
[CrashReport.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/6216393/CrashReport.zip)
Crashed while taking a fireball in the middle of an execution. Eesh.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/112736676-73d60d00-8f22-11eb-8b0e-51978668babc.png)
right click the folder, security tab, edit permissions, and give yourself full control.  And the stealth kill through the doors is fixed in the current development state for v21.10.0 I dont go back and update the old version on moddb(v21.9.0).

**Comment by BLOODWOLF333** [comment]
Closing, can't duplicate the issue
