### ISSUE TITLE
Misaligned Meshes in Doom 1993 with GZDoom

### ISSUE THREAD

**Issue by Quantum303** [BLOODWOLF333/Brutal-Doom-Community-Expansion#296]
### Version 21
using the stable version.

### Environment
occurs on a computer. Windows 10 64 bit OS. Using Steam version of Doom 1 (1993), running using ZDL version 3-1.1.

### Port
this occurs on GZdoom.

### Description
I've noticed several misaligned meshes in E1M1 and M2 (so far; it may occur as I continue playing). The helicopter in E1M1 is supposed to be burning, but the flaming animation occurs about six feet _away_ from the helicopter itself. As for E1M2, I've noticed several windows floating above the floor/ground; that is to say, they are not positioned at the actual window sill where they should be. Pictures of E1M1 attached because I'm terrible at describing.
![Screenshot_Doom_20210404_000951](https://user-images.githubusercontent.com/64048111/113500334-55e84980-94da-11eb-969f-f1f6ff03a19c.png)
![Screenshot_Doom_20210404_001043](https://user-images.githubusercontent.com/64048111/113500335-5680e000-94da-11eb-9f98-f09fd2e7d48e.png)
![Screenshot_Doom_20210404_001051](https://user-images.githubusercontent.com/64048111/113500336-5680e000-94da-11eb-9ab0-cb6d743d7244.png)

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20210404_013127](https://user-images.githubusercontent.com/16950832/113500690-aca75080-94e5-11eb-83e9-31fbf1269c53.png)
![Screenshot_Doom_20210404_013141](https://user-images.githubusercontent.com/16950832/113500692-b03ad780-94e5-11eb-9260-16bba3703fe6.png)
Something is wrong in your options because I am not able to duplicate that.  Reset all your stuff to default and try again.

**Comment by Quantum303** [comment]
Thank you for the lightning-fast response! I resetted everything to default and I'm still seeing the screwed up windows.
![Screenshot_Doom_20210404_083141](https://user-images.githubusercontent.com/64048111/113512092-4d1a6680-9520-11eb-933f-d199290678e2.png)

**Comment by BLOODWOLF333** [comment]
I have no idea, your the first one to report this so maybe get a clean download of GZDoom and v21.9.0 or what is your load order/what other wads are you combining with this?

**Comment by Quantum303** [comment]
![Screenshot_Doom_20210408_192158](https://user-images.githubusercontent.com/64048111/114115279-bfcc6e80-989f-11eb-9f9b-35dab1c2295b.png)
Completely deleted my entire installation and started from scratch, GZDoom and v21.9.0, the works. I'm not combining this with any wads, just dragging and dropping brutalv21.9.0.pk3 onto GZDoom and I still get the screwed up windows.

**Comment by BLOODWOLF333** [comment]
Using GZDoom 4.5.0 or what version?

**Comment by Quantum303** [comment]
Yes, GZDoom 4.5.0, Windows 10 64bit.

**Comment by Quantum303** [comment]
![Screenshot_Doom_20210408_194140](https://user-images.githubusercontent.com/64048111/114116769-7b8e9d80-98a2-11eb-8c08-b509b40f56f2.png)
Did some messing around. It seems to correct itself when I use the Vulkan API and the Hardware accelerated render mode (under Display options).

**Comment by BLOODWOLF333** [comment]
That's really weird cause I am not able to duplicate the issue at all on my end and I have Win 10 64 bit as well.  You were using software render before?

**Comment by Quantum303** [comment]
Correct. I basically cycled through all APIs and render modes until I got it to work.

**Comment by BLOODWOLF333** [comment]
ok, and do you have some kind of brand new graphics card or something special in anyone else runs into this issue and needs to switch to Vulkan?

**Comment by Quantum303** [comment]
It's not what I'd call new (couple years old), but for the record it's an AMD Radeon RX 560 series card.

**Comment by BLOODWOLF333** [comment]
Ok yeah I looked it up and thats kind of a fancy advanced gaming graphics card with Vulkan so maybe its going to require that render mode.  I asked the online chat assistant dude and he pointed me to emailing their tech support to find out why and that it was way above his pay grade lol.  But, now I know what to tell people if this issue comes up again.
