### ISSUE TITLE
Brutal Simple 4:3 doesn't show grenade ammo

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#298]
### Version
-master

### Environment
PC

### Port
LZDoom  v3.87c

### Description
![Screenshot_Doom_20210414_213109](https://user-images.githubusercontent.com/76774186/114761621-69f93a00-9d69-11eb-9664-f2d5033d7b1f.png)

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/114786770-5091c700-9d44-11eb-8557-216cb6f34f55.png)
Go into hud options and set the stretch status bar to full screen to yes

**Comment by Nic-Usor** [comment]
Ok
