### ISSUE TITLE
Ability to punch while in Revenant form.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#3]
Description: When under the effect of a Revenant Morph Rune, players are quite vulnerable at close-range, only able to fire missiles and risk killing themselves with the splash damage. They also lack the ability to punch that real Revenants have. And yet the Baron can do both ranged and melee without issues.

**Comment by BLOODWOLF333** [comment]
![rev_punch](https://user-images.githubusercontent.com/16950832/84602085-8a572000-ae4a-11ea-9205-b039d77aedb8.png)
From TypicalSF
