### ISSUE TITLE
The revenant corpse disappear in the liquid

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#300]
### Version
-master

### Environment
PC

### Port
LZDoom v3.87c

### Description

https://user-images.githubusercontent.com/76774186/115626660-7d2a7d80-a306-11eb-991b-b59366a3013d.mp4

**Comment by BLOODWOLF333** [comment]
Are you able to consistently reproduce this?  It's spawning the torso piece for me after sawing the corpse.

**Comment by BLOODWOLF333** [comment]
And the Archvile's corpse (dying with no arm) is the one I am able to consistently reproduce and have seen occur in-game several times but, didnt realize liquid was triggering the issue.
