### ISSUE TITLE
Punching the shotgunguy on head don't make fatality even if having berserk

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#301]
### Version
brutalv21.10.0_dev

### Environment
PC

### Port
Zandronum 
### Description

https://user-images.githubusercontent.com/76774186/117554329-a1ed5780-b05f-11eb-86dd-375f638d6115.mp4

**Comment by BLOODWOLF333** [comment]
Yeah I've noticed this but its not a bug.  If you hit the headshot actor it explodes with a damagetype of "head" which is correct.

**Comment by Nic-Usor** [comment]
Ok, but you can fix it thq kick giving a head?

**Comment by BLOODWOLF333** [comment]
Lol no not really.  You had berserk so your kicks were the berserk version of the kick projectile which does the damagetype "extremepunches" same as the non-fatality berserk punch which will give you the zombiemanhead.  I would have to give the berserk kick a different damage type and then create a pain and death state of that damagetype in every single monster file and any other actor file that has various states for various damagetypes.  Its not something simple and not worth it for the goofy head weapon.  Mark is working on v22 so, maybe this will be taken out or maybe the berserk kick will get its own damagetype and solve this oversight.

**Comment by BLOODWOLF333** [comment]
ok was messing with this and the berserk kick give you the head I fixed.  and the fatalities on headshots is impossible to fix.  the actor who killed the monster with the damagetype of fatality is who the monsters gives the tokens for what fatality animation to perform.  if the headshot actor is the one killing it with fatality damage then the player doesnt do the fatality animation and it screws things up.
