### ISSUE TITLE
Switching from dual wielding make weapon unusable.

### ISSUE THREAD

**Issue by Real-Gecko** [BLOODWOLF333/Brutal-Doom-Community-Expansion#302]
### Version
v21.9.0 Stable

### Environment
PC, winduz

### Port
GZDoom 4.5.0, Zandronum Dev3.1-200501-1847

### Description
- Select any dual wield able weapon (eg: 4 - assault rifle)
- Dual wield it (`X` is my shortcut)
- Switch to another weapon (eg: 3 - shotgun)
- Try to select previous weapon once more (eg: switch back to assault rifle with 4)
- Nothing happens
- ????
- NO PROFIT

**Comment by BLOODWOLF333** [comment]
I'm not able to reproduce this at all with the current version or with 21.9.0.  What player class, are you picking these weapons up like on the test map or using the IDFA or IDKFA cheat?  Are you pressing the number key and or the prev/next weapon keybind?  I tried it with Zand 3.0 and GZDoom 4.5.0.  And what is your load order in case another addon is messing with this?

**Comment by Real-Gecko** [comment]
Hey, I've uploaded video demonstrating the issue, it shows both BD21 Gold and 21.0.9 one after another with key strokes on the screen, hope it helps https://youtu.be/0FkTawI1swc
Maybe it has something to do with my config, I've uploaded GZDoom ini too(note that I changed extension to `txt` as GitHub does not want to upload `ini`.
[brutal.txt](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/6488178/brutal.txt)
Also thing to note that it's saved, if I fuck by switching from dual wielding, `loose` my weapon and save then it's gone forever, however if I reload latest auto or quicksave I'll have my weapon back. To avoid the issue I now switch back to single weapon and then switch, this way no issue happens.

**Comment by BLOODWOLF333** [comment]
yeah it has to be something on your end, I watched your video and tried to duplicate the problem exactly as shown and I cant recreate it over here with the current state of 21.10.0 or the old 21.9.0 on GZDoom or Zand.  As long as you dont have any other mods in your skins folder that would mess with the KEYCONF file (which is the weapon order for brutal doom) then make a new .ini or start a new game.  I know new versions will break old saved games commonly but you started a new game in the video so it's probably your .ini file.

**Comment by Real-Gecko** [comment]
But as you can see in the video it works in BD21 Gold with the same config file.

**Comment by BLOODWOLF333** [comment]
I have significantly changed how dual weapons work compared to Gold.  Before gamepad and mobile users couldn't scroll through their weapons if they dual wielded, they had to switch back to single to then change weapons. I made it take the single weapon and give the dual and added the duals to the KEYCONF file so they can prev/next weapon like normal.  try deleting your .ini file and letting it compile a new one or redownloading GZDoom and retest cause I cant fix something that I cant duplicate.

**Comment by Real-Gecko** [comment]
OK, now I see the logic behind your changes, whenever I press `X` (my dual wielding hotkey) double weapon replaces single one so slot 4 for example is occupied by `DualRifles` and not `Rifle` from now on, if I posses `DualRifles` and hit `X` again the change is reverted. The problem in my config was that section where I reorder my weapon choices did not contain `dual` variants:
```ini
[Brutal_Doom.BDoomer.Weapons]
Slot[1]=DSweap Melee_Attacks BrutalAxe Chain_saw ClassicFist ClassicSaw
Slot[2]=BrutalPistol ClassicPistol ClassicSMG Revolver MP40 BrutalSMG
Slot[3]=Shot_Gun AssaultShotgun SSG ClassicShotgun ClassicSSG
Slot[4]=Rifle Minigun Machinegun ClassicChaingun HitlersBuzzsaw
Slot[5]=GrenadeLauncher Rocket_Launcher ClassicRocketLauncher NukeLauncher
Slot[6]=Railgun Plasma_Gun ClassicPlasmaRifle
Slot[7]=BFG10k BIG_FUCKING_GUN Unmaker VanillaBFG9000
Slot[8]=FlameCannon HellishMissileLauncher Flamethrower2
Slot[9]=HandGrenades
```

I've adjusted it to look like so:
```ini
[Brutal_Doom.BDoomer.Weapons]
Slot[1]=DSweap Melee_Attacks BrutalAxe Chain_saw ClassicFist ClassicSaw
Slot[2]=BrutalPistol DualPistols ClassicPistol ClassicSMG Revolver2 Revolver ClassicMP40 MP40 DualMP40 BrutalSMG DualSMG
Slot[3]=Shot_Gun AssaultShotgun SSG ClassicShotgun ClassicSSG
Slot[4]=Rifle DualRifles Minigun Machinegun ClassicChaingun ClassicBuzzsaw HitlersBuzzsaw
Slot[5]=GrenadeLauncher Rocket_Launcher ClassicRocketLauncher
Slot[6]=Railgun Plasma_Gun DualPlasmaRifles ClassicPlasmaRifle
Slot[7]=NukeLauncher BFG10k BIG_FUCKING_GUN VanillaBFG9000
Slot[8]=HellishMissileLauncher Unmaker ClassicUnmaker
Slot[9]=FlameCannon FlameThrower2
Slot[0]=HandGrenades
```
And now everything works like charm, thanks for the help, man!
