### ISSUE TITLE
One shot headshot for knights

### ISSUE THREAD

**Issue by Real-Gecko** [BLOODWOLF333/Brutal-Doom-Community-Expansion#303]
### Version
v21.9.0 Stable

### Environment
PC, winduz

### Port
GZDoom 4.5.0, Zandronum Dev3.1-200501-1847

### Description
In 21 Gold I usually was able to oneshot hell knights with direct head shot from SSG, now it's not the case, sometimes takes two, is it a bug or a feature?

**Comment by BLOODWOLF333** [comment]
I dont know why I had the Damagefactor for SSG set to 1.5 in the headshot actors.  set it back to 5.0

**Comment by Real-Gecko** [comment]
Thanks, man!
