### ISSUE TITLE
The enemy legs hitbox is weird

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#305]
### Version
Brutal-Doom-Community-Expansion-master

### Environment
PC
### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
When shoot the enemy legs has weird hitboxes

https://user-images.githubusercontent.com/76774186/118296128-47338000-b4e5-11eb-9bf1-0ece1fa37007.mp4

**Comment by Nic-Usor** [comment]
Is happen to use shotgun.

**Comment by BLOODWOLF333** [comment]
ok, well they should be transferring more damage than they should, like the small monsters should die from a shotgun blast to the leg and not be able to weather 4 of them.  So, that is fixed and I assume that is what your reporting?  "weird hitboxes" is kinda vague.

**Comment by Nic-Usor** [comment]
I'm sorry, I am not good at english.

**Comment by BLOODWOLF333** [comment]
thats ok but the problem was 'leg hitboxes being extremely tough and taking too many shots" right?  Cause thats what I just fixed.

**Comment by Nic-Usor** [comment]
Ok
