### ISSUE TITLE
ExplosiveBarrel tweaks (again)

### ISSUE THREAD

**Issue by vsonnier** [BLOODWOLF333/Brutal-Doom-Community-Expansion#309]
Hello again @BLOODWOLF333 ,

I've revisited the `ExplosiveBarrel1` because after more practical testing un maps, I realized that `A_CheckSight` was not enough, and worse, ruined the gameplay.

There are indeed quite a lot of situations where the Player blows off a visible Barrel close but not too close, which in turns blows up others close to it ( Yeah, MAP23 Barrel O' Fun but with smarter placement). 

In such a typical situation, those other Barrels are either hidden, or the Player quickly hides behind a structure not to be blown up by the series of explosions.

With just `A_CheckSight` well the first Barrel goes Kaboom but the others goes off Meh which is quite a disappointment.

There is no perfect solution for this, but this is what I finally did for Black Edition:
- If the Barrels are _reasonnably_ close (A_CheckRange) they blow up with all the effects. I chose 1000 units.
- If the Barrels are beyond that distance, AND they are visible (A_CheckSight), also use the full effects
- else use the reduced effects Barrels.

Such solution won't save you if:
-  You have a ton of hidden barrels at proximity going off, all hidden.
-  You have a Barrel reaction from a far distance, with one Barrel visible and plenty of others hidden:  First, this is a special case that is not that common, and second since you are far the reduced effects won't register that much visually.

The code looking something like this :

```asm
Death:
        BAR4 A 1
	//
	TNT1 A 0 A_CheckRange(1000, "DeathPlayerIsFar")
DeathFullEffects:	
        ... the rest of the full effects
	Stop
	
	//
DeathPlayerIsFar:	
	TNT1 A 0 A_CheckSight("DeathReducedEffects")
	Goto DeathFullEffects
DeathReducedEffects:	
      ... reduced effects version 
     Stop
```  

Tested with Sunlust MAP30, it doesn't change much of the duration of the freeze at start. On the other hand in real maps the gameplay is restored in its full glory.

**Comment by BLOODWOLF333** [comment]
If 30c1062 didnt work then reopen this issue.

**Comment by vsonnier** [comment]
It is fine, thanks.
