### ISSUE TITLE
Spritefixes and visual consistency, for v0.2.0

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#31]
### Description
Would it be possible to integrate the following spritefixes and additions, for visual consistency in the next stable release?

-Rotation and idle sprites for Pistol Zombie (by Theundeadsoldier)
-Additional fixes and idle sprites for SMG Sergeant (by Dox778)
-Unique magazine ejections for Pistol, Rifle, and ASG (by Dox778)

**Comment by BLOODWOLF333** [comment]
yeah, the pistol and ASG drum i can take from XV117's Enhanced Weapons Mutator.  See if you can get them to upload the files to this issue.

**Comment by Shockwave508** [comment]
Dox778 said you could still use his zombie sprites; I'm posting them here for easier access.
[Dox778_SMGPistolZombies_BD.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/4778854/Dox778_SMGPistolZombies_BD.zip)
