### ISSUE TITLE
New enemy spawn level option is not implemented correctly

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#311]
### Version
Stable v21.10.0.

BTW, thank you for the new release. Your dedication is always appreciated.
### Environment
Computer.

### Port
Zandronum

### Description
Brutal Doom Options > BD Level Options > New Enemies

From what I can tell it looks like this option is only telling some enemies like the Volcabus, Ancient Arachnotron, etc. to simply go into the `Stand` state when "nonewenemies" is 1. Regardless of this option being enabled/disabled the Volcabus and Ancient Arachnotron will appear in Ultimate Doom maps like E3M6. The fix would be to remove these actors from the map if this option is in the disabled state.

I'm aware this option may be antithetical to the spirit of Brutal Doom however options should always do what they say they will do.

**Comment by BLOODWOLF333** [comment]
So the new enemies options will spawn the vanilla Doom enemies which do not have BD's attacks like the demon's and imp's lunges or the baron's triplefireball.  Those Ultimate Doom new monster spawns are part of the map enhancement spawns but, I may be able to make them comply with the no new enemies cvar.
