### ISSUE TITLE
Murdered by friendly marine

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#313]
### Version
v21.10.0.

### Environment
Computer.

### Port
Zandronum

### Description
I had a rocket marine (beige colored suit) on E1M9 on Ultimate Doom and he killed me via an explosion. I don't know if it was from his rocket launcher backblast or he hit the barrel in the room where there is a switch behind 4 barrels that I was near (it's the one near the wall but in front of those ones). Nothing out of the ordinary and all the Pinky demons were still near the keycard while I was mowing them down with a chaingun from afar. This was the first time I've encountered a rocket marine so I'm not too familiar with their behavior.

Before I knew what was going on he then spent the rest of his time punching the shit out of my corpse, tearing Pinky demons limb from limb that got in the way, and then saying "yeah, got ya bitch!" while using my corpse as a punching bag. Over and over. I could only watch in amazement.

Probably just a bad coincidence but it may be worth looking at if some of these guys will fire their weapon in front of a barrel or possible want to target the player somehow. All I can say is he was definitely locked on targeting something that was already dead.

**Comment by BLOODWOLF333** [comment]
Lmao that is epic I dont want to "fix" that.  I made sure that their projectiles including back-blast and explosive damagetypes are all of the type "friendbullet" which the player takes 0.0 from.  But, if they hit a barrel....it was probably accidental because barrels have the +FRIENDLY flag and marines wont target them.  I think that's hilarious though the rocketmarine is a badass.

**Comment by KJeff01** [comment]
>probably accidental

_Probably_? That marine know **exactly** what he was doing. Was one of the funniest things I've seen in a game in a long time though.

Anyway, I wanted to make sure the projectiles were working as intended. So I'll close this.
