### ISSUE TITLE
Enhanced taunt induced behavior?

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#315]
### Description
What if taunting an enemy (default keybind H seems to do at least something) made them angry and they would enter a state where they could, I don't know,

1. Move and/or perform thinking and actions faster.
2. Use more intelligent AI, new abilities, or suddenly use new weapons.
3. Projectiles do more damage and/or have faster flight speed.

If I taunted a shotgun guy I'd expect him to get pissed off: commonly rolling to avoid weapons pointed near them, chucking grenades, maybe even taunting the player if he killed them (bonus points if he flipped you off, lol). Cacodemons might try flying at you for a bite (like how they suddenly veer off to the side to avoid a hit... that kind of speed). And so on.

Also, adding a game option that lets all enemies act like this at all times for good times sake.

Don't know if mods could do all of this. Just wanted to share the idea and see what you think. Would be a fairly ambitious project but would be way cool.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/120045115-d60bc680-bfd4-11eb-8dc1-4891056dd69b.png)
this is already implemented.  the humanoid monsters who would even understand a taunt/insult will +MISSILEMORE +MISSILEEVENMORE and attack more frequently or enable the fast movement flag.  Mark's logic is that cacos and non-humanoid monsters wouldn't react I think I remember him saying on the discord or somewhere.  And I never use taunts so, I wouldn't get any benefit from this.
