### ISSUE TITLE
Enemies can be injured if you press E (use/open)

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#316]
### Version
brutalv21.10.0.pk3

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
If you press e, enemies will be injured or, rarely, dead if you get close to them.

https://user-images.githubusercontent.com/76774186/120047935-8a7e0a80-c01e-11eb-8f53-2b3a17cff47a.mp4

**Comment by BLOODWOLF333** [comment]
Yeah theyre getting hit by the invisible Stealthattack projectile that you fire when you press use and I've been googling and reading the zdoom wiki and we dont have a way to change a monster's DamageFactor or PainChance to a specific damagetype on the fly in-game.  limited game engine.

**Comment by BLOODWOLF333** [comment]
Asked on the Zandronum discord and Zandronum doesn't support anonymous functions in Decorate yet and that would have only allowed me to change the general purpose damagefactor to all damagetypes instead of just specifically "Stealth".  There's no way to fix this without breaking stealth kills.
