### ISSUE TITLE
Some Zombieman Fatalities bodies disappear on fluids

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#319]
### Version
brutalv21.10.0

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
Some Zombieman Fatalities bodies disappear on fluids

https://user-images.githubusercontent.com/76774186/120064921-73b7d200-c077-11eb-8608-e002ea6efa95.mp4

https://user-images.githubusercontent.com/76774186/120064927-7a464980-c077-11eb-8f26-7dad466921af.mp4

https://user-images.githubusercontent.com/76774186/120064992-c5f8f300-c077-11eb-9f1a-88bee4af02c6.mp4

**Comment by BLOODWOLF333** [comment]
The dyingarchvilenoarm was/is doing this too and I attempted to fix it previously.  check that the archvile's brutalized actor isn't still doing this as well.  I dont really understand why these actors are disappearing over liquids to begin with.

**Comment by Nic-Usor** [comment]
I tested them all doomguy fatalities on monsters, and they are fine on liquid (except doomguy fatality on revenant when he pulls out a hand and hits it on the head and the corpse destroys itself)
