### ISSUE TITLE
One barrel SSG shot + unload + load loads only 1 barrel

### ISSUE THREAD

**Issue by Zodomaniac** [BLOODWOLF333/Brutal-Doom-Community-Expansion#32]
### Version
Stable 0.1.0

### Environment
Win7 x64

### Port
GZDoom 4.4.0

### Description
Fire one barrel of SSG (altfire), unload it and then load. The animation will look like reloading a single shell, and only 1 shell will be loaded instead of 2.

**Comment by Zodomaniac** [comment]
@BLOODWOLF333 I have the fix, it's just 1 line, but why don't you let me create branches anymore?

**Comment by BLOODWOLF333** [comment]
all you have to do is click the fork button to have your own branch and can create pull requests that way without needing repository access.

**Comment by Zodomaniac** [comment]
Created a pull request: https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/pull/39
