### ISSUE TITLE
Axe never spawn when killing Scientist Zombie on fluids and when shoot in the abdomen disappears

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#320]
### Version
brutalv21.10.0.pk3

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
When you kill Scientist Zombie on fluids never spawn axe and when shoot in the abdomen disappears and remains guts.

https://user-images.githubusercontent.com/76774186/120065817-078b9d00-c07c-11eb-87d1-33bc6bab99d3.mp4

**Comment by BLOODWOLF333** [comment]
this all is probably related to #319 with BD actors having problems spawning over liquids.
