### ISSUE TITLE
If you have explosive weapons and shoot the on floor, ceiling and walls besides enemies never shows extra sprites

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#322]
### Version
brutalv21.10.1

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
When you have a rocket launcher, grenade launcher or throw a grenade and shooting on floor, ceiling and walls besides enemies (zombieman, shotgunguy, chaingunguy, imp, labguy, hell knight and baron of hell) never shows extra sprites like this:
![Screenshot_Doom_20210531_171344](https://user-images.githubusercontent.com/76774186/120534108-25ddf980-c3ea-11eb-9529-1f4f06b69808.png)
![Screenshot_Doom_20210531_171708](https://user-images.githubusercontent.com/76774186/120534109-26769000-c3ea-11eb-9415-dc477790e632.png)
![Screenshot_Doom_20210531_172021](https://user-images.githubusercontent.com/76774186/120534111-270f2680-c3ea-11eb-98df-a6a91e41400d.png)
![Screenshot_Doom_20210531_172046](https://user-images.githubusercontent.com/76774186/120534117-27a7bd00-c3ea-11eb-8cf3-1378aadcaa30.png)
![Screenshot_Doom_20210531_171237](https://user-images.githubusercontent.com/76774186/120534119-28405380-c3ea-11eb-81b9-b5d65560395f.png)
![Screenshot_Doom_20210531_171250](https://user-images.githubusercontent.com/76774186/120534120-28d8ea00-c3ea-11eb-9cb8-8a1016113764.png)
![Screenshot_Doom_20210531_171313](https://user-images.githubusercontent.com/76774186/120534121-28d8ea00-c3ea-11eb-9bce-9d3ee7e65919.png)
![Screenshot_Doom_20210531_171331](https://user-images.githubusercontent.com/76774186/120534124-28d8ea00-c3ea-11eb-8092-735edad98ada.png)

But, you shooting on ceilings they never take damage.

**Comment by Nic-Usor** [comment]
P.S.: I'm using the original Brutal Doom v21.

**Comment by BLOODWOLF333** [comment]
....what?????

**Comment by Nic-Usor** [comment]
When you shoot an explosive weapon at the floor, walls or ceiling next to enemies never show gibs sprites.

https://user-images.githubusercontent.com/76774186/120555527-df959400-c403-11eb-85e8-da6e2ddd0e15.mp4

**Comment by BLOODWOLF333** [comment]
Did they used to in v21 Gold?  I dont see what the problem is here.  Why would I waste my ammo no corpses in the first place?

**Comment by Nic-Usor** [comment]
Yes, I'm using the v21 Gold.
