### ISSUE TITLE
Sometimes, Imp execution disappear

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#323]
### Version
brutalv21.10.0.pk3

### Environment
PC

### Port
Zandronum 3.0 and LZDOOM v3.87c

### Description
Sometimes, Imp execution disappear, but if you do execution with some enemies they show Imp hiting on wall.

https://user-images.githubusercontent.com/76774186/120535747-047e0d00-c3ec-11eb-955a-ddb30f06b0b9.mp4

**Comment by BLOODWOLF333** [comment]
I've been fighting with this one for over a year idk why it keeps disappearing
