### ISSUE TITLE
Several assets cut off on ultra-wide displays

### ISSUE THREAD

**Issue by colinmahns** [BLOODWOLF333/Brutal-Doom-Community-Expansion#332]
### Version
Stable, 21.10.3 (also tested on 21.10.1 and 21.10.2)

### Environment
Desktop PC, Debian 11

### Port
GZDoom 4.6.0

### Description
Revenant's rockets are cut off on ultra-wide displays when used by the player. Most other assets are able to scale well, but as these come from the corner of the screen it's much more noticeable when moving to displays with different aspect ratios. 

![Screenshot from 2021-09-05 00-13-05](https://user-images.githubusercontent.com/1781677/132115098-79119fe5-9d15-4bd7-b12f-74e3eca9d479.png)

**Comment by BLOODWOLF333** [comment]
Do the vehicle HUDs do this as well?  I Imagine the artillerytank HUD would have this problem too.

**Comment by BLOODWOLF333** [comment]
I dont have a super-wide monitor and cant duplicate this but, the rest of the sprites just aren't drawn and I suck at drawing on the computer.  So, this is backburner until someone can finish them.

**Comment by colinmahns** [comment]
Great thinking, I rarely use the vehicles so I didn't think to look, was mostly playing with the weapons since I noticed a similar issue in Freedoom last night as well. 

Both the tanks (normal and artillery tank) seem to be affected. The walker also has a text placement issue but that may be unrelated. Helicopter and motorcycle, as well as turrets, seem to be fine. Should I rename this issue to make this a more general issue?

tank: 
![cannonhe-at](https://user-images.githubusercontent.com/1781677/132133879-53e71f0a-ae4e-4642-88e4-e67f92c44f0a.png)
artillerytank:
![artillerytank](https://user-images.githubusercontent.com/1781677/132133878-d3bc674a-97c8-4db4-b60f-d62ccbf787a1.png)
walker (may be a seperate issue?)
![walker](https://user-images.githubusercontent.com/1781677/132133877-509a4f2d-e9b1-4c24-983c-d504bd659dc2.png)

**Comment by BLOODWOLF333** [comment]
Do you get the same result when you play with the Zandronum port (which is all that I develop for)?  I know GZD has some goofy ass confusing options but I just have a 16:9 1920x1080 monitor so, Im not really going to be able to test a fix.

**Comment by colinmahns** [comment]
I actually can't get it started on my ultrawide with Zandronum after forcing it to open in full screen, not sure if I have a config option or something that's messed up with it. Works fine on the 16:9 I have plugged in on the side

**Comment by colinmahns** [comment]
I actually can't get it started on my ultrawide with Zandronum after forcing it to open in full screen, not sure if I have a config option or something that's messed up with it. Works fine on the 16:9 I have plugged in on the side. Will have to look at it later more in depth. 

Here's the output from my terminal

`cmahns@colin-desktop:~/Downloads$ zandronum DOOM2.WAD brutalv21.10.3.pk3 
Gtk-Message: 13:40:55.849: Failed to load module "canberra-gtk-module"
Zandronum 3.0.1 - 191013-1938 - SDL version
Compiled on Nov  3 2019
Using video driver x11

M_LoadDefaults: Load system defaults.
Can't find './nerve.wad'
W_Init: Init WADfiles.
 adding /usr/games/zandronum/zandronum.pk3, 689 lumps
 adding ./DOOM2.WAD, 2935 lumps
 adding DOOM2.WAD, 2935 lumps
 adding brutalv21.10.3.pk3, 15503 lumps
 adding brutalv21.10.3.pk3:dmlevels.wad, 118 lumps
 adding brutalv21.10.3.pk3:psxlevels.wad, 42 lumps
 adding brutalv21.10.3.pk3:testmap.wad, 13 lumps
I_Init: Setting up machine state.
CPU Vendor ID: GenuineIntel
  Name: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Family 6, Model 158, Stepping 9
  Features: MMX SSE SSE2 SSE3 SSSE3 SSE4.1 SSE4.2
I_InitSound: Initializing FMOD
FMOD Sound System, copyright � Firelight Technologies Pty, Ltd., 1994-2009.
Loaded FMOD version 4.24.16
OSS could not be initialized. Trying ALSA.
V_Init: allocate screen.
Using in-memory database. The database will not be saved on exit.
S_Init: Setting up sound.
ST_Init: Init startup screen.
Checking cmd-line parameters...
S_InitData: Load sound definitions.
G_ParseMapInfo: Load map definitions.
Texman.Init: Init texture manager.
ParseTeamInfo: Load team definitions.
LoadActors: Load actor definitions.
Script warning, "" line 0:
Invalid face '' for 'Doomer';
STF replacement codes must be 3 characters.

Script warning, "" line 0:
Invalid face '' for 'Doomer';
STF replacement codes must be alphanumeric.

R_Init: Init Doom refresh subsystem.
DecalLibrary: Load decals.
DistX in slider decal Drops is unsupported
PWO_Init: Initializing preferred weapon order.
M_Init: Init menus.
P_Init: Init Playloop state.
ParseSBarInfo: Loading default status bar definition.
ParseSBarInfo: Loading custom status bar definition.
D_CheckNetGame: Checking network game status.
player 1 of 1 (1 nodes)
Initializing network subsystem.
IP address 127.0.1.1:10667
UDP Initialized.
The program 'zandronum' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 176 error_code 2 request_code 152 minor_code 10)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)


*** Fatal Error ***
Address not mapped to object (signal 11)
Address: (nil)

Generating zandronum-crash-09_05_2021-13_41_06.499110.log and killing process 499110, please wait... sh: 1: gdb: not found
sh: 1: gdb: not found
sh: 1: gxmessage: not found
Killed
`

**Comment by BLOODWOLF333** [comment]
There's talk of and someoone made a hacky patch for ultrawide for gzdoom but, asked on the zandronum discord as well and there is no "elegant" way to adapt BD's sprites for ultrawide.  Like the tank I could just make the sides blacked out but that defeats the point of ultrawide and is sloppy. 
https://forum.zdoom.org/viewtopic.php?f=18&t=51086

**Comment by BLOODWOLF333** [comment]
vid_allowtrueultrawide false
might give that a try in the console for GZDoom as well
https://forum.zdoom.org/viewtopic.php?f=50&t=71377

**Comment by BLOODWOLF333** [comment]
Closing, I dont believe there is any way I can elegantly fix something like this may just be a port-limitation regarding rendering ultra-wide.
