### ISSUE TITLE
Flashlight and friendly marine interaction

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#335]
### Version
v21.10.3.

### Environment
Computer

### Port
Zandronum.

### Description
Flashlights interact strangely with friendly marines. If you shine a flashlight on a friendly marine for about a second it will go through them on a repeated basis.

I did an experiment and found the hitbox properties of friendly marines are cycled. If I shoot at them while the light is behind one it will not affect them though when the light is cycled to appear on them they produce blood splatter. Making me believe the longevity of friendly marines is in part due to them being hard to hit cause something turns off their hitbox on a timer basis. This may be intended I guess but the flashlight should stay on them at all times like with every other "solid" object.

**Comment by BLOODWOLF333** [comment]
Yeah thats done on purpose and is how Mark originally coded them

**Comment by BLOODWOLF333** [comment]
Made the flashlight projectile (which have the dynamic lights attached to them) move through the marines at all times now so that it is consistent.
