### ISSUE TITLE
Using a SSG and killing a Cacodemon is still alive in 3 sec instead to kill instantly

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#342]
### Version
brutalv21.10.3

### Environment
PC
### Port
Zandronum and LZDoom

### Description
https://user-images.githubusercontent.com/76774186/133943482-7889839b-eedd-4718-b44a-288547be6e6b.mp4

**Comment by BLOODWOLF333** [comment]
Dude thats the DyingCacodemon actor that you can further kill to get cruelty bonuses that is intentional.
