### ISSUE TITLE
Monsters that have colored blood spawn red blood only the Zandronum

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#348]
### Version
v21.11.0 Stable

### Environment
PC

### Port
Zandronum 3.0

### Description
When you have a explosive weapons or using the turret and shoot the monsters that have colored blood they spawn red blood , and friendly marine holding firearms and explosive weapons spawn red blood when they shooting monsters that have colored blood (only Zandronum have this bugs). I tested on LZDoom and work fine.

**Comment by BLOODWOLF333** [comment]
I am not able to duplicate this at all in v21.11.0 with Zandronum.

**Comment by KJeff01** [comment]
I think he means something like if you shoot a rocket at a Cacodemon that it should spawn blue blood when it takes a hit and survives. They'll spawn red blood in this situation unlike bullets.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20211021_000048](https://user-images.githubusercontent.com/16950832/138214431-578a6f57-2924-4e09-9643-7387c613a0c9.png)
yeah, I'm not seeing that.  I play test online every night on TSPG and haven't seen this happen at all.

**Comment by BLOODWOLF333** [comment]
I'm able to duplicate it now and having been going around in circles trying to fix it for the last couple of hours.  Not sure why this is happening yet
