### ISSUE TITLE
When shooting with Unmaker never hit on the floor and the ceilling

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#354]
### Version
v21.11.1 Stable-Patched

### Environment
PC

### Port
Zandronum and LZDoom

### Description

https://user-images.githubusercontent.com/76774186/142484636-31581b1c-7113-49de-8381-d61cb254d6a8.mp4

**Comment by BLOODWOLF333** [comment]
I know, I've tried to make the attack puff on floors at least several times and it doenst work.  A_RailAttack() doesnt allow for that and there's nothing I can do to "fix" it.
https://zdoom.org/wiki/A_RailAttack
