### ISSUE TITLE
Blackmetal/Realism difficulty ignores user Reload Animation setting

### ISSUE THREAD

**Issue by KJeff01** [BLOODWOLF333/Brutal-Doom-Community-Expansion#355]
### Version
v21.11.1.

### Environment
Computer.

### Port
Zandronum.

### Description
Standard game with a Rifle start.

Seems the Blackmetal and Realism modes override my setting to enable reload animations when a mission loads. Loading a new game with Nightmare and UltraViolence afterwards will show the reload animations. So, it's not like my config option is being overwritten in the file at least.

I'll also note that if I set it to enable reload animations while in a game with anything at Blackmetal or stronger it will show the animations but if I load into the next mission it will skip the animations again.

**Comment by BLOODWOLF333** [comment]
Yep, I screwed this one up.  Someone complained about cyberdemons dying from headshots from the ASG too quickly on BlackMetal+ difficulties so I messed with them and overlooked that they all would be forced to have the turboreload inventory item.
