### ISSUE TITLE
Friendly marine when shooting monsters doesn't have blood particle

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#356]
### Version
Brutal-Doom-Community-Expansion-master

### Environment
PC

### Port
LZDoom and Zandronum

### Description

https://user-images.githubusercontent.com/76774186/142739399-2c8ae19d-399d-41ba-b032-eaae6b4be270.mp4

**Comment by BLOODWOLF333** [comment]
this is what you wanted and the result of fixing the dumb increased gore feature.  the friendly marines shoot tracers like the monsters do so they cant have the +BLOODSPLATTER flag or else you will see a bunch of red blood appear when they shoot a blue or green blood monster.
