### ISSUE TITLE
SMG Zombie never reloading

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#357]
### Version
Brutal-Doom-Community-Expansion-master

### Environment
PC

### Port
LZDoom and Zandronum

### Description
I waited 2 minutes to see if SMG Zombie reloading but he doesn't.

**Comment by BLOODWOLF333** [comment]
because no reload animation sprites exist for the SMG zombie to have a reload state.  If you create them I will add them

**Comment by Nic-Usor** [comment]
I hope you like it. I'm using Adobe Photoshope and Brutal Doom resource.

[SMGGuy Reloading Sprites.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/7575462/SMGGuy.Reloading.Sprites.zip)

**Comment by BLOODWOLF333** [comment]
![PSS3B1](https://user-images.githubusercontent.com/16950832/142744436-c2b924d0-b377-4ae8-9378-ac9aaad488de.png)
use this sprite

**Comment by Nic-Usor** [comment]
Thanks, now I made it. I hope you like it. I'm spending 30 minutes for this.

[SMG Guy Reloading Sprite.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/7576428/SMG.Guy.Reloading.Sprite.zip)
