### ISSUE TITLE
Some boss monster and vehicle enemies are immune from explosive barrels

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#358]
### Version
v21.11.1 Stable-Patched

### Environment
PC

### Port
Zandronum and LZDoom

### Description
Some boss monsters and vehicle enemies are immune from explosive barrels such as:
Cyberdemon

https://user-images.githubusercontent.com/76774186/142776577-3e23504c-178c-4fee-896a-ec94daa7a33b.mp4

Juggernaut

https://user-images.githubusercontent.com/76774186/142776523-a4d9b7a6-9e5e-40f1-a9e0-8f01834e23b5.mp4

The Spider Mastermind

https://user-images.githubusercontent.com/76774186/142776536-e23ac8f3-7a96-4503-b96a-24707e62db1f.mp4

Zombie helicopter

https://user-images.githubusercontent.com/76774186/142776553-ce1a0bf5-d8d5-4bcb-aa07-e75ba8daf816.mp4

Zombie mech

https://user-images.githubusercontent.com/76774186/142776561-dbc4d02a-700c-4560-b62f-ada9fd98b2d8.mp4

Zombie artillery tank

https://user-images.githubusercontent.com/76774186/142776570-cc031311-980e-4749-a463-d85cda17207e.mp4

And Zombie main battle tank

https://user-images.githubusercontent.com/76774186/142776599-41a94a7e-01bd-474c-8446-aea9991e9889.mp4

**Comment by BLOODWOLF333** [comment]
```NORADIUSDMG
Actor cannot be hurt by radius (explosive) damage.```
https://zdoom.org/wiki/Actor_flags
boss monsters have had this flag since vanilla 1993 Doom that is working as designed.
