### ISSUE TITLE
Dual Wield Bug Locks Out Weapons

### ISSUE THREAD

**Issue by ColonelSandersLite** [BLOODWOLF333/Brutal-Doom-Community-Expansion#365]
### Version
Present in 21.11.1 and 21.10.3

### Environment
PC

### Port
GZDoom 4.7.1 x64

### Description
Start Doom 1 E1M1

IDKFA

Kill some zoms to get a second pistol.

Equip Pistol.

Activate Dual Wield.

Switch to shotgun *without going back to single wield*.

You now can't reequip a pistol.

This also happens with rifles and smgs.  I haven't checked any other dual wield weapons but I'm assuming it applies to all of them.

**Comment by BLOODWOLF333** [comment]
What else are you loading?  With 21.11.1 IDKFA is going to give you dual weapons for all that apply and you wouldnt need to activate dual wield.  I have changed the KEYCONF file so that dual weapons will allow Android and gamepad users to prev/next weapon hotkey through with duals equipped which they were not able to do before in standard brutalv21.

**Comment by ColonelSandersLite** [comment]
My command line is
gzdoom.exe -iwad wads\doom.wad -savedir saves\doom1 -file wads\brutalv21.11.1.pk3

So just loading doom.wad and brutalv21.11.1.pk3

**Comment by BLOODWOLF333** [comment]
I'll have to download GZD4.7.1(they love to break things that were never broken before) tomorrow and take a look, in zandronum and GZD4.5.0 I couldnt duplicate this.

**Comment by ColonelSandersLite** [comment]
I figured it out.  It's my fault.  You modified the way that weapon selection on the slots works I didn't realize it.  Due to this, my old weapon setup from vanilla v21 didn't have the dual weapons defined in the weapons slots.

The scripting behind the scenes to manage weapon selection sometimes correctly disables selecting the single versions of weapons when you press your weapon slot key and since I didn't have the dual versions in my weapon slots, they couldn't ever be selected.
