### ISSUE TITLE
No grenades in Ozonia? 

### ISSUE THREAD

**Issue by Skrell** [BLOODWOLF333/Brutal-Doom-Community-Expansion#367]
### Version
Latest stable. 

### Environment
Win10 PC

### Port
GZDOOM 4.7.1

### Description
Hi there, I'm not 100% sure this is a bug but I'm hoping you might have some idea... I'm trying to play through Ozonia with your BD mod, but have noticed that I NEVER find or pick up any grenades?   Could this be because of something Ozonia did with their mapset?   https://www.doomworld.com/forum/topic/103371-ozonia-boom-megawad-rc3-out/

**Comment by BLOODWOLF333** [comment]
I have grenades
![Screenshot_Doom_20220117_193045](https://user-images.githubusercontent.com/16950832/149855390-37f0886e-cdf3-40fc-ab5e-c718f43bb46a.png)
Are you loading it before brutalv21?
![image](https://user-images.githubusercontent.com/16950832/149855236-e5fe2325-ff14-4042-bb1f-e38a93b34e1d.png)
But, grenades will rarely be dropped by zombiemen and shotgunguys, rarely spawn in place of the single rocket pickup and ammo backpacks also give grenades.

**Comment by BLOODWOLF333** [comment]
I think I reduced their probability of showing up except from backpacks compared to normal brutal doom but, I will abuse the hell out of these chucking them around corners and clearing rooms so I made them more precious but not overly so.

Zombieman = 4/256 chance to drop a grenade, v21 gold doesnt drop them at all
shotgunguy = 4/256 chance, v21 gold had a 15/256 chance
AmmoRocketReplacer = 4/256 chance, v21 gold single rocket ammo is just vanilla
backpack gives 1 grenade, v21gold the backpack gives 3 grenades so that's probably the biggest reduction you might see
and I reduced the max capacity to 3(6 with backpack) from v21 golds max of 20 (thats crazy to walk around with that many grenades hanging off your gear)

**Comment by Skrell** [comment]
Ok based on the odds you're saying I guess it is entirely possible I'm just getting unlucky.  Unfortunately I do think the grenades add a lot to the tactical gameplay so is there any way you can make them more common?  Or possibly add an option where the user can specify what other items randomly get replaces by grenades?

**Comment by BLOODWOLF333** [comment]
I've never played through that wad before but, did the author really skimp on backpacks in it?  And this is all done with decorate code and ACS (all I play is Zandronum coop with the wife so I will never give up compatibility with zandornum) so, there's no elegant way of doing all that complex stuff.  Have to remember the author probably didnt intend you to play this wad with brutal doom but, you can always cheat like the wife and I do each night and go to the test map to load-up first then warp to the level we left off on the previous night when working through a wad.
I could create a grenade ammobox actor(which already exists) to rarely spawn in place of the rocketbox but, if your not getting backpacks or rocket ammo in your playthrough then it wont help.  We play every night and I haven't noticed being starved for grenades that I can remember.

**Comment by Skrell** [comment]
Let me try another megawad and I'll get back to you.  Ty for the quick and thorough responses!

**Comment by Skrell** [comment]
Also, any idea why all the weapon sound mod packs I found for BDv21 don't seem to have any effect when loaded after your mod?

**Comment by BLOODWOLF333** [comment]
No, would have to look at what all they were changing I dont use any of them.

**Comment by Skrell** [comment]
Would you mind giving this one a try?  (although I've tried many)
https://www.moddb.com/mods/brutal-doom/addons/brutal-doom-black-edition-weapon-sound-for-brutal-doom-v21

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/150029841-27537ec2-eb7b-45af-addc-43ad900b157d.png)
they dont work because I created a female tired sound for tactical class and that is causing the error.  Can either //notate out the male and female tired lines in brutalv21.x like in the screenshot or just add those lines to the sndinfo of those sound mods and it will then work fine.

**Comment by Skrell** [comment]
Ok, I'll make the fix.   Try this one:
https://www.moddb.com/mods/brutal-doom/addons/kickass-weapon-sounds

**Comment by BLOODWOLF333** [comment]
These sound mods dont benefit me I dont use them.  I assume this issue is resolved then?

**Comment by Skrell** [comment]
My apologies, you're right this isn't your issue it's mine.  Nevertheless, the BE sound fix didn't work.  To be clear, I added/modified the following to its included SNDINFO.BD:

//PlayerSounds
$playersound	player	male	*death		dspldeth
$playersound	player	male	*xdeath		dspdiehi
$playersound	player	male	*gibbed		dsslop
$playersound	player	male	*grunt		dsoof
$playersounddup	player	male	*land		*grunt
$playersound	player	male	*jump		dsoof
$playersound	player	male	*fist		dspunch
$playersound	player	male	*usefail	dsnoway
$playeralias	player	male	plpain		Pain1
$playersound	player	male	tired		TIRED

$playersound	player	female	*death		DSFDETH
$playersound	player	female	*xdeath		DSFDIEHI
$playersound	player	female	*gibbed		dsslop
$playeralias	player	female	*grunt		DSFEMUF
$playersound	player	female	*land		DSF2OOF
$playeralias	player	female	*jump		DSFEMUF
$playersound	player	female	*fist		dspunch
$playeralias	player	female	*usefail	DSFEMUF
$playersound	player	female	*taunt		dsftaunt
$playeralias	player	female	plpain		DSFPAIN
$playersound	player	female	tired		TIRED

**Comment by Skrell** [comment]
Nm, I just went into the pk3 and deleted the entire SNDINFO.BD file and that seemed to work!

**Comment by BLOODWOLF333** [comment]
ah, yeah if they didnt change any of the sound names that is a much more simple work around.  get Notepad++ for free with the Compare plugin and that makes life easier when comparing text files between mods to immediately see all the differences and quickly figure out what you have to add/delete to make them compatible.
