### ISSUE TITLE
Do you add nazi gores?

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#368]
### Description
In Brutal Doom, nazi gore sprites replaced with gore sprites from the shotgunguy. Also, I'm found nazi gore sprites from Project Brutality. Check out if you like it.
[NAZIS.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/7900994/NAZIS.zip)

**Comment by BLOODWOLF333** [comment]
No, there is hardly any difference and Im not OCD enough for this to bother me its fine the way it is.
