### ISSUE TITLE
Oculus quest 2 vr weapon support..

### ISSUE THREAD

**Issue by HUNGfLO** [BLOODWOLF333/Brutal-Doom-Community-Expansion#369]
Dont know how to exactly put this, but running anything besides brutalv21 gold w vr weapons crashes the game.  Can you mod or make a version that just uses the brutalv21 weapons only w all the other upgrades?  Or test to see if this is exactly why it crashes?  Would love to try an updated version of bd.  Thank you!

**Comment by BLOODWOLF333** [comment]
I dont do VR so can't test, your going to have to try to screenshot the error or copy and paste the console start-up log so I can see how to fix it.  Looking in the file right now and I see that it patches over all the weapon decorate files so all of those would have to be updated and I dont know how to do any of the Quake III modeling stuff so cant change those.

**Comment by HUNGfLO** [comment]
I can screenshot the log, im not asking for modeling or the such.. maybe just a reversal for quest to bd21 weapon set..  im guessing that w the 3d weapons is the conflict, because it only crashes when I check vr weapons..  otherwise sprites load and work just fine.  I really think its the extended weapon library giving the issue.  And man you shld try doom in vr..  its pretty fn sweet.

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/file/d/1u-lbr0_RqbVbhktw0z7fygo9zC2wVjkm/view?usp=sharing
Ok I just deleted all the weapon decorate files out of this that it was overwriting, added modeldefs for the slug version of each shotgun, and fixed the errors in all the modeldefs.  This isnt done yet because I have added and modified a few frames of animation for some weapons but this will at least let you keep playing right now.  Ill touch this up more over the weekend.

**Comment by BLOODWOLF333** [comment]
and it sure seems like the rocket launcher, bfg, and machinegun models are way to high on the screen testing this on the computer.  are they too high in VR as well?

**Comment by HUNGfLO** [comment]
Yo man, thank you for the quick action!  Really appreciate you and your efforts!  Vr weapons as far as placement in vr is fine.  Ill take a look at the pk3..  oh and load order?(i can generally figure that out, but does it just replace bd21.x.x?)  Again thank you.

**Comment by HUNGfLO** [comment]
Hell yea!  No pun intended, but it works and theres a 3d model i havent seen before?  The mp40 so thats even cooler!

Side note right now, but when you shoot marines generally the green haired ones in the head their upper body explodes.  Can you plz take a look and fix this issue.  Thank you again.. and ill let you know if I come across anything else.  Awesome work!

**Comment by HUNGfLO** [comment]
Yea something is really off w the dmg system.  Headshots w the pistol automatically blow marines upperbody in half and shotguns only make shotgunners fly.  Its like alot of the bd animations and dmg sprites are gone.  Is that because you had to mess w it?  And if so is it fixable?

**Comment by HUNGfLO** [comment]
Also the 3d boot isnt there and for some reason and the ledge grab mod is conflicting

**Comment by BLOODWOLF333** [comment]
what about ledge grab is conflicting?  Its not always possible to maintain compatibility with everything because of how this old 1994 code is and I only play online with zandronum so GZDoom only things I cant guarantee compat with.

**Comment by BLOODWOLF333** [comment]
> Hell yea! No pun intended, but it works and theres a 3d model i havent seen before? The mp40 so thats even cooler!
> 
> Side note right now, but when you shoot marines generally the green haired ones in the head their upper body explodes. Can you plz take a look and fix this issue. Thank you again.. and ill let you know if I come across anything else. Awesome work!

Im not seeing zombiemen (green hair) upper bodies explode when shooting them in the head with a pistol (or are you using the revolver which I gave 100-damage magnum ammo for).

**Comment by BLOODWOLF333** [comment]
> Also the 3d boot isnt there and for some reason and the ledge grab mod is conflicting
> 
> And sorry idk if i answered, but the original vr weapons were animated.. shotty loads shells ssg folds.. chaingun spins etc

![image](https://user-images.githubusercontent.com/16950832/150623547-7b0ff2c5-e42c-4691-bdb2-0b6ec81c2127.png)
there are no included models for a 3D boot

**Comment by HUNGfLO** [comment]
Not sure why.. the 3d boot is in v21(that or the 3d weapons pack that is included in the quest z launcher)  How do you switch ammo..  is it button config?  But the ar and smg are doing the same..  blowing them in half.  
I don't want to sound like a broken record, but ledge grab works w v21..  i have no idea why it would conflict now?  Also as far as dropped weapons they all seem to be the same as you hold..  not voxel if selected in bd options.  Is that how it is now?  And if so can we get them or the option to not rotate? Maybe sit on or closer to the ground?  And maybe take a look at where they are spawned from(in regards to the sprite..  seems to spawn too high).  Hope your friday has been goin gud btdubs.

**Comment by BLOODWOLF333** [comment]
That weapon pickup rotating in air is in the 3D model files and I dont have any model software.  If you are playing black metal or one of the hard realism difficulties then everythings damage is increased and could be why theyre exploding enemies but, just normal ultra violence stuff is working normally. 
Changing ammo for all shotguns is now triggered by the dual wield keybind.
I know ledge grab is done with scripting and I have messed with BD's scripts quite a bit to make everything smoother so that probably broke compatibility.  So the ledge grab mod author would need to update his mod if he even cares about it working with mine.  I dont play GZDoom so these other mods dont benefit me in any way.

**Comment by HUNGfLO** [comment]
Yea i play on the realism..  ill have to test, but i did figure put how to switch ammo.  The over the top gibbin kinda is a bummer that it breaks the game on realism..  shld just behave like bd21, but further optimized?  Kind of strange to mod it that much(just my opinion).  For the dropped weapons, its a bummer the 3d rotating guns are there, theyre weird and out of place..  atleast rotating.  Wish I could just switch it to voxels, but they seem to be over ridden for some reason.  As for ledge grab..  makes sense.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/150625920-5a3a5a8a-caad-46ee-af07-179cc435de86.png)
I dont know, normal bdv21 monsters have half hitpoints as well.  Your always free to make your own patch and change things to how you like.  It's impossible to make everyone happy I've been trying to do that for 3 years now lol.
and the BFG10k is bugged and will crash in that version I linked above, just fixed it in the one I'm working now.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/150652411-323e3911-6d02-42b2-b343-8daa1a422633.png)
the rifle model in this mod is screwed up dude, they have it offset by half a degree so aiming down the sights is never going to look right on this thing

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/file/d/1ajl6SIaGJ-85toj9FQ_zXuM3v7cp0cmR/view?usp=sharing
Ok, rifle aim down sights model is fixed and it all lines up now
weapon pickups are the 3D models, their height is lowered and they dont rotate anymore
rifle zoom reduced to 1.3 from the x4.0 in my mod(i added an ACOG to the rifle in the expansion)
I lowered all the HUD models to where weapons would be normally in doom with sprites so I can actually see them on the computer, let me know if they need to be raised back up for VR which I cant test.
every weapons zoomed-in models have been lined-up with your actual crosshair, again hopefully this matches up in VR

**Comment by BLOODWOLF333** [comment]
https://drive.google.com/file/d/1Gl3fgks0E1G3fWNmyN8CWDnNhSKLb2k2/view?usp=sharing
I seen I was working on an outdated version of that VR weapon pack so this is an updated version of the latest stable.  Let me know if the aim down the sights actually lines up with your point of aim in VR

**Comment by HUNGfLO** [comment]
Hey man,  thank you for noticing that.  This ver. Actually stopped the guns rotating and put them on the ground!  Heck yea!  There is one thing tho..  the guns are a bit low and could go slightly back into the hand.  Hope you had a good weekend..  didnt want to bother and was really busy w fam stuff anyways.

**Comment by HUNGfLO** [comment]
I had another question for you.. its about project brutality.  You may know where to look, but inside of questzdoom you can load the mod, but when you turn your character(snap turn) loses their movement plane where normally you snap and its the new axis for movement.. pb loses it or stays w the original plane.  If you think you know where to look or to fix that.  It would be amazing for quest users.  Thank you for your time..

**Comment by HUNGfLO** [comment]
Oh actually one more thing about brutal doom..  this version the imps appear to have too much life..  im guessing like by 20-30%  they take a bunch of headshots w ar..  funny feeling for the pace.  Playing on plain uv to let you know..  everything else seems fine.

**Comment by BLOODWOLF333** [comment]
> Hey man, thank you for noticing that. This ver. Actually stopped the guns rotating and put them on the ground! Heck yea! There is one thing tho.. the guns are a bit low and could go slightly back into the hand. Hope you had a good weekend.. didnt want to bother and was really busy w fam stuff anyways.
![Screenshot_Doom_20220124_165033](https://user-images.githubusercontent.com/16950832/150878100-e1f67d12-9d97-41a8-bc61-467de2e051ab.png)
So on the computer I cant see the VR hand or anything so I lined up all the weapons when not aiming down the sights with this BFG that has that nice flat spot on the top of the weapon that I can use to level all the other weapons off of.  Do all the weapons even when not aiming down the sights need to be lined up with the crosshair(red dot)?  Or maybe move up to halfway between where that BFG is sitting and the crosshair?

**Comment by BLOODWOLF333** [comment]
> I had another question for you.. its about project brutality. You may know where to look, but inside of questzdoom you can load the mod, but when you turn your character(snap turn) loses their movement plane where normally you snap and its the new axis for movement.. pb loses it or stays w the original plane. If you think you know where to look or to fix that. It would be amazing for quest users. Thank you for your time..

I have no idea (I dont like project brutality) and don't have VR to diagnose any of that

**Comment by BLOODWOLF333** [comment]
> Oh actually one more thing about brutal doom.. this version the imps appear to have too much life.. im guessing like by 20-30% they take a bunch of headshots w ar.. funny feeling for the pace. Playing on plain uv to let you know.. everything else seems fine.

Didnt change the imp health any, still at 80 hitpoints, they do take x5.0 damage from head shots so 2 rifle hits kill them I just tested now.

**Comment by HUNGfLO** [comment]
Ok.. sry i sent a few msgs, but in order..  originally the weapon placement was spot on..  and its hard to explain unless you can see it in vr, but yes bedt placement was how it was og.  Second..  i understand if you dont like vr..  just thought w your knowledge it maybe like an oh yea they just needed this line of code here and voila, but your gud man.  And third.. how do I get the updated version for imps?  And thanks for that tweak!  Id like to toss you a $20 or something..  how would i go about doing that?

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/150887398-6f2b394f-5fbc-4c66-bc67-8863540a3d3b.png)
v21.11.3 on left, brutalv21 on right
my brutalv21.11.2 or above has the "updated" imps already, all I did was normalize damagefactors (kinda like resistances and weakenesses) across all the monsters but, Imp's hitpoints are the same.
And we cannot make money off of modding a commercial product thats kind of illegal.
So I will revert all the weapons back to their original height offsets then (which puts the model over the players eyes on computer and you cant see anything).

**Comment by BLOODWOLF333** [comment]
https://github.com/BLOODWOLF333/br_vr/releases/tag/B40
Ok it has been updated and all the weapons have been moved back up to their original heights except for the Mp40, Rifle(I need to know if aiming down the sights in VR matches the crosshair position on computer, I assume it does which would mean putting the rifle back to its og height would misalign the aiming sights) and rocketlauncher so that their sights line-up with the crosshair (again that I assume matches your crosshair on PC)

**Comment by HUNGfLO** [comment]
Sry bro, was busy and thinking of a way to show you.. as the tracer was aove the vr weapon completely(above carrying ar handle of the ar)..  originally er the one that comes w quest it was spot on..  and to answer the ads part it was alined nicely for ads.  As for ads as a button it makes the weapon model move up and down really quick w each button press of alt fire.

**Comment by HUNGfLO** [comment]
Theres no crosshair in vr, but they added a laser sight mod that works amazing.. and again naturally aiming is spot on w all thw guns..  of course the rocket and bfg are bulky, but work well.

**Comment by HUNGfLO** [comment]
I wanted to give you a tip.. are you ok w that?  I mean for your time.

**Comment by HUNGfLO** [comment]
> ![image](https://user-images.githubusercontent.com/16950832/150887398-6f2b394f-5fbc-4c66-bc67-8863540a3d3b.png) v21.11.3 on left, brutalv21 on right my brutalv21.11.2 or above has the "updated" imps already, all I did was normalize damagefactors (kinda like resistances and weakenesses) across all the monsters but, Imp's hitpoints are the same. And we cannot make money off of modding a commercial product thats kind of illegal. So I will revert all the weapons back to their original height offsets then (which puts the model over the players eyes on computer and you cant see anything).

Sry i dont see the "new" imp version to dl?

**Comment by HUNGfLO** [comment]
Ohhh..  i just need to dl same version.

**Comment by BLOODWOLF333** [comment]
> Ohhh.. i just need to dl same version.

![image](https://user-images.githubusercontent.com/16950832/150904575-398245c7-36c9-4e7a-be79-5affaca459bf.png)
I mean my imps have been like that for 15 months now there havent been any updates to their toughness at all.  normal brutal doom v21 gold had the monster damagefactors all over the place and they were not consistent.  this was all a long time ago can go on zdoomwiki.org and that explains actor properties and damagefactors a lot more in depth.  nothing major has changed about the imps

**Comment by HUNGfLO** [comment]
Ok, im confused.  So the imps take 2 headshots to kill?  Its always been that way?  Or you changed it?  It takes around 7-8 headshots on v 21.1.2 or the most recent when i play on uv.

**Comment by HUNGfLO** [comment]
> > Ohhh.. i just need to dl same version.
> 
> ![image](https://user-images.githubusercontent.com/16950832/150904575-398245c7-36c9-4e7a-be79-5affaca459bf.png) I mean my imps have been like that for 15 months now there havent been any updates to their toughness at all. normal brutal doom v21 gold had the monster damagefactors all over the place and they were not consistent. this was all a long time ago can go on zdoomwiki.org and that explains actor properties and damagefactors a lot more in depth. nothing major has changed about the imps

Can I show you that imps arent having their damage factors take effect?  I know you said theyve been that way for 15 months, but I dont have to try to recreate.. its really, all imps.  Is it that way on pc?  Anyways hope to hear from you soon..  and until then have a gud day, man.

**Comment by BLOODWOLF333** [comment]
id recommend to go on the test map to the targets and see if the weapons are lined up with your point of aim I have a feeling they are not.  If an imp gets shot in the head and doesnt die it will duck and put it's hands over its head Im wondering if your hitting the body.  and you really are the best person to get these weapons lined-up if they are off because I cant see.
![image](https://user-images.githubusercontent.com/16950832/151067390-c313d78e-3c33-45f3-9fd6-dbea73557dfd.png)
Slade is free to download and then you just open the BDCE_VR_Quest_B40.pk3 and go in to change the ZOffset for each weapon to get them lined up if this is the issue.

**Comment by HUNGfLO** [comment]
thats exactly what happens..  they repeatedly duck.  Ill make a short video for you.  I can shoot everything else in the head..  marines die in one headshot..  its just the imps really.. its 6-8 shots..  pretty much acting like the headshot multiplier isnt working for imps?  If the videos arent the best let me know and i can adjust options to make it better quality thru a work around.  Second video at the end shows red dot aiming and accuracy..  looks pretty clean.

**Comment by HUNGfLO** [comment]
I posted them to my facebook.. quick way since oculus links to it.  My name is josh bravo..  let me know if you cant find my facebook or the vids.  I dont use it at all.

**Comment by BLOODWOLF333** [comment]
> I posted them to my facebook.. quick way since oculus links to it. My name is josh bravo.. let me know if you cant find my facebook or the vids. I dont use it at all.

There are a lot of Josh Bravos on there and it wont let me look, I dont have facebook either.  Like I dont even have a smart phone I reject big tech and all their invasive technology now days Im honestly the wrong person to work on VR stuff.

**Comment by BLOODWOLF333** [comment]
And even with just the pistol, two shots to the head and the imps die testing on computer so, what other mods are you loading besides brutalv21.11.2?

**Comment by HUNGfLO** [comment]
Ill look, but there shld be nothing that mods away from brutal dooms core..  textures, door mod, music, standard wads, double jump, voxels & patch, flashlight, psy..weaponwheel,  pbimps..(you think pbimps could do it?  Its only supposed to add the jumping to roof), but im not bsing you for a moment and i posted videos.  I can try and get them to youtube..  ill let you know when theyre up.  I agree w the social media stuff.

**Comment by HUNGfLO** [comment]
Oh and is there a 3rd or more ammo types for shotgun?  I saw a box of shotgun shells that were yellow and maybe a white one?

**Comment by BLOODWOLF333** [comment]
> Ill look, but there shld be nothing that mods away from brutal dooms core.. textures, door mod, music, standard wads, double jump, voxels & patch, flashlight, psy..weaponwheel, pbimps..(you think pbimps could do it? Its only supposed to add the jumping to roof), but im not bsing you for a moment and i posted videos. I can try and get them to youtube.. ill let you know when theyre up. I agree w the social media stuff.

its probably that pbimps mod, this old 1994 code is not as simple and modular as just adding the ability to wall/roof walk it replaces the entire imp file to write-in new states in the actor's code.

**Comment by BLOODWOLF333** [comment]
> Oh and is there a 3rd or more ammo types for shotgun? I saw a box of shotgun shells that were yellow and maybe a white one?

the 3rd ammo type that says "magnum" on the box are for the revolver that rarely spawn in place of the shellbox.

**Comment by HUNGfLO** [comment]
Oh ok..  i couldnt tell what it said for sure.  Thanks man and ill check and see if thats the issue..  running pbimps.

**Comment by HUNGfLO** [comment]
Hey man, hope your year has started off well and wanted to say hello.  Hmu w any links also if theres anything new or you recommend trying mods/addons etc.Sent from my T-Mobile 4G LTE Device
-------- Original message --------From: Carr ***@***.***> Date: 1/29/22  1:18 PM  (GMT-07:00) To: BLOODWOLF333/Brutal-Doom-Community-Expansion ***@***.***> Cc: HUNGfLO ***@***.***>, Author ***@***.***> Subject: Re: [BLOODWOLF333/Brutal-Doom-Community-Expansion] Oculus quest 2 vr weapon support.. (Issue #369) 
Closed #369.
