### ISSUE TITLE
Trying to replace chaingun sounds

### ISSUE THREAD

**Issue by Skrell** [BLOODWOLF333/Brutal-Doom-Community-Expansion#370]
Hi again, I'm sorry to bother you but I've been trying to figure out how to change your chaingun sounds effects but can't seem to figure it out.  I've gone and deleted ALL your sounds that have the prefix "chain__" and "chgn__" and I STILL hear the gun firing, so those sounds must be coming from somewhere else?

**Comment by BLOODWOLF333** [comment]
CHGNSHOT is the fire sound
![image](https://user-images.githubusercontent.com/16950832/153770033-c1fa4f31-f6cb-47f8-99f6-6de7de238169.png)

Simply rename wtvr sound your wanting to use instead to CHGNSHOT and load it after brutalv21.11.x and it will work

**Comment by Skrell** [comment]
But then why does deleting chgnshot NOT stop the sound from coming out?

**Comment by BLOODWOLF333** [comment]
why are you deleting stuff?  
https://zdoom.org/wiki/SNDINFO
read that article before modifying things.  I cant see and don't know what your doing so your going to have to explain it.

**Comment by Skrell** [comment]
I was simply deleting sound files to see which files contributed to the chaingun shooting sound.  I figured once it stopped making sound, I knew which files were the ones that affected the shooting sound. Now that you showed me minigun.txt I realize that perhaps the scripting(?) of the sounds make a big impact on the overall sound?

**Comment by Skrell** [comment]
I figured out what's wrong!  For some reason firing the chaingun uses the sound DISTANTSOUNDS/FARMGN.ogg instead of CHGNSHOT!   Any idea why this is??

**Comment by BLOODWOLF333** [comment]
oh, yeah all the weapons fire a distant sound effect that is a custommissile.  I think in 21.11.2 there is an issue with the minigun's (close range) fire sound getting drowned out by the distant echoing sound and I have that fixed in 21.11.3.  So, if that is what your trying to fix then can just re-download this repo and save as a .pk3 and you will have the fix and the most up to date version.  I will release v21.11.3 this weekend probably.

**Comment by Skrell** [comment]
Great thank you!

**Comment by Skrell** [comment]
Just curious, how did you fix it?

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/153974404-21228182-968c-456c-b312-fc978b2bc3c0.png)
change the $Limit to 0

**Comment by Skrell** [comment]
All this does is remove the close chaingun sound... leaving ONLY the FARMGN.ogg .  Is that what you wanted ?

**Comment by BLOODWOLF333** [comment]
no it sets the limit of the close-range CHGNSHOT to infinite so that the FARMGN sound wont override/drown-out the close-range sound.  played through 2 megawads with it this way online and it works correctly.  why do you want to remove the CHGNSHOT sound?

**Comment by Skrell** [comment]
My apologies... I thought that $limit was meant to limit the max number of simultaneous instances of a sound being played.  So by putting a value of 0 it would mean at most 0 instances of this sound can play at a time.

**Comment by BLOODWOLF333** [comment]
> My apologies... I thought that $limit was meant to limit the max number of simultaneous instances of a sound being played. So by putting a value of 0 it would mean at most 0 instances of this sound can play at a time.

![image](https://user-images.githubusercontent.com/16950832/154160751-fd6eb60c-1702-44fd-8843-4e58800f10d4.png)

**Comment by Skrell** [comment]
Correct, so I think you need to go and update ALL of your $limit lines in SNDINFO.BD bc the values of 70 you had really did nothing.

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/154161261-f6157275-4427-418c-9065-776837f08e0a.png)
its at 0 for CHGNSHOT not 70 what are you talking about?  The other weapons are at 70 but who cares they never have any problems even online.

**Comment by Skrell** [comment]
Would you please explain what these paths mean in SNDINFO.BD ?   I don't see any directories that match this? 

ie)
weapons/ssg/open
weapons/ssg/close
weapons/ssg/in	
weapons/ssg/fire

**Comment by BLOODWOLF333** [comment]
those are from vanilla doom.  Open your GZDoom or zandronum.pk3 and will find a SNDINFO in them for Doom, Heretic, Hexen, and Strife with everything in that <category>/<sub-category>/<name> format

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/154178044-c55fac06-845b-43f7-b192-3eeca473cfd9.png)
filter/game-doomchex dude I have other things to do I cannot teach you how to do this.  read read read the zdoom wiki which is how I taught myself.
