### ISSUE TITLE
Problems with the items and weapons drop animation

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#373]
### Version
v21.11.3 Stable-Patched

### Environment
PC

### Port
Zandronum 3.1 and LZDoom

### Description
Some items and weapons has no drop animation and they skipped them.

https://user-images.githubusercontent.com/76774186/155901221-b3d5f636-c52c-4298-9cde-d21f251cd83d.mp4

**Comment by BLOODWOLF333** [comment]
Because none exist except for the rifle only.  This isnt a bug.
![image](https://user-images.githubusercontent.com/16950832/155901896-d07d8314-3199-4515-8ab3-c73680dcef9e.png)
