### ISSUE TITLE
The hanging corpse damages the player when you shoot them

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#377]
### Version
v21.11.3 Stable-Patched

### Environment
PC

### Port
Zandronum 3.1 and LZDoom 3.88b

### Description
Actors like DeadHangNoGuts, DeadHangBNoBrain, DeadHangTLookingDown, DeadHangTLookingUp, DeadHangTSkull and DeadHangTNoBrain takes damage when you hit or shoot close to him.
For, example:

https://user-images.githubusercontent.com/76774186/158064614-da006cbb-619e-4cfd-8cd3-1d1ef558c41f.mp4

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/158069862-8e19ac9c-514d-4a44-a82d-f10529f269ea.png)
Mark has them doing explosive damage for some reason idk, I'll remove that from them
