### ISSUE TITLE
Corpses disappear at teleport destination

### ISSUE THREAD

**Issue by Nic-Usor** [BLOODWOLF333/Brutal-Doom-Community-Expansion#378]
### Version
v21.11.3 Stable-Patched

### Environment
PC

### Port
Zandronum 3.1 and LZDoom 3.88b

### Description

https://user-images.githubusercontent.com/76774186/158064837-5743084d-f8d1-4cbb-a699-7e975cca0ab3.mp4

**Comment by BLOODWOLF333** [comment]
....looks like theyre just falling behind that teleport pad

**Comment by Nic-Usor** [comment]
This bug cause when teleport destination thing is on monsters thing.
![teleport destination thing](https://user-images.githubusercontent.com/76774186/158074021-8f4d8aed-5912-44c4-af5b-a4508b3f2c16.png)

https://user-images.githubusercontent.com/76774186/158074026-dbff79b6-ea0f-4059-9585-f24fa464eeb3.mp4

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/158074358-74013c5e-75eb-4d2f-857d-38a1ba5be80b.png)
Looks like Mark made it do this on purpose in teleports.txt to keep the pads clear I guess idk he doesnt remember why he did things this way or that any time I ask him why something was done a certain way.

**Comment by Nic-Usor** [comment]
Probably, he made decals from teleportation when player entering, I guess.
![PNTGA0](https://user-images.githubusercontent.com/76774186/158074678-c5383b6c-3689-45b9-a10d-bbf1177ad4fd.png)
![PNTGB0](https://user-images.githubusercontent.com/76774186/158074681-e46e9118-ddc9-4ace-b602-3f46084f67b2.png)

**Comment by BLOODWOLF333** [comment]
Yeah those appear on the ground when you teleport somewhere.  I dont think this is wrong he prob wanted to keep the pads clear of bodies because they could cover them up in a slaughterwad as an example.
