### ISSUE TITLE
Dual Rifles: Bottom edge of sprites is visible.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#38]
### Version
Dev Snapshot v0.1.1

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.85

### Description
When brandishing the Dual Rifles, the bottom-edge of their sprites can be seen. Screenshot attached.
![Screenshot_2020-06-15-02-36-02](https://user-images.githubusercontent.com/32436386/84630601-ce314000-aeb1-11ea-8866-079bb34d3550.png)

Additionally, the Assault Rifle's sprite offsets are messed up when switching to the Dual Rifles.

**Comment by BLOODWOLF333** [comment]
"Additionally, the Assault Rifle's sprite offsets are messed up when switching to the Dual Rifles."
Messed up how other than they are too high?

**Comment by Shockwave508** [comment]
The sprites being too high fits the bill for "messed up", at least in my eyes.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20200615_203237](https://user-images.githubusercontent.com/16950832/84721905-69c0c000-af47-11ea-8d4b-bce5b7b5cb04.png)
Issue is not present on Zandronum

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20200615_204236](https://user-images.githubusercontent.com/16950832/84722428-cf617c00-af48-11ea-8755-7b859f0b220a.png)
And am not seeing that in GZDoom 3.7.1 either

**Comment by BLOODWOLF333** [comment]
Maybe a mobile or new version of GZDoom issue.

**Comment by Zodomaniac** [comment]
This is not the case in GZDoom 4.4.0. 
![Screenshot_Doom_20200616_202629](https://user-images.githubusercontent.com/15119473/84807499-ff278700-b00f-11ea-9639-3da8eecc77fb.png)

**Comment by BLOODWOLF333** [comment]
I asked Dox about this and he said his dual rifle sprites are higher.  Before reporting a bug isolate it to just this mod with everything else removed so nobody is chasing their tale looking for a problem that doesnt exist in this mod in the future.
