### ISSUE TITLE
Arachnotron turns into an Ancient Arachnotron when fatalitied by a friendly marine

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#388]
### Version
Stable - v21.12.0

### Environment
Mobile (Delta Touch v4.6)

### Port
GZDoom v4.7.1

### Description
When taken down with a Berserk Execution, a normal Arachnotron will morph into an Ancient Arachnotron, and will leave behind an Ancient Arachnotron corpse once the animation finishes.

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20220418_224230](https://user-images.githubusercontent.com/16950832/163915926-e5ae62cd-a706-4b35-a518-4a2d3a35820d.png)
![Screenshot_Doom_20220418_224232](https://user-images.githubusercontent.com/16950832/163915929-d4bea1be-d306-41c0-aaba-b9a68c2f7451.png)
![Screenshot_Doom_20220418_224317](https://user-images.githubusercontent.com/16950832/163915930-107b9bee-5f90-4da3-a7a9-52b0cf2062c9.png)
What?
