### ISSUE TITLE
Client side Demon Spheres option

### ISSUE THREAD

**Issue by BlackRNG** [BLOODWOLF333/Brutal-Doom-Community-Expansion#391]
i think demon spheres are annoying, optional var to disable them on client side would be nice

**Comment by BLOODWOLF333** [comment]
They are annoying and you already can disable them in Brutal Doom Level Options

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/166329061-9e836a74-b7d7-4550-a23e-22e6ae51431f.png)

**Comment by BlackRNG** [comment]
i mean when you join a server that has them enabled, and you accidentally step on them

**Comment by BLOODWOLF333** [comment]
You can setup and host your own server for free on allfearthesentinel.net and not have to play with other people's goofy rules which is what i do, I dont like how other people do things so I host my own.  Its hosted on their server farm hardware and I always had demonspheres disabled cause yes they are annoying.  I dont feel like its worth the time to overcomplicate how the demonspheres work I dont play with them on and dont really care about em.  Hopefully Mark rips em out in v22 and then I will remove them from mine as well.
![image](https://user-images.githubusercontent.com/16950832/166331618-d982ac1b-36fb-4d67-bb7a-f7773002fff0.png)
