### ISSUE TITLE
[Feature Request] Support Doom CE

### ISSUE THREAD

**Issue by telanus** [BLOODWOLF333/Brutal-Doom-Community-Expansion#393]
I tried BDCE with PSX Doom Final CE mod and it works, sort off. The main problem is once you pick up the key cards the game don't recognize that you have the keycard.  It works perfectly if I play the Mod without Brutal Doom CE, so something between the two mods clash. 

Would love if this mod could support that mod. 

Mod download linky: https://www.moddb.com/mods/doom-ce/downloads/doom-ce-321-lite-version

**Comment by BLOODWOLF333** [comment]
![image](https://user-images.githubusercontent.com/16950832/176969954-f1e08780-c6ff-4691-a9e5-7fef3858a7cd.png)
that mod changes the lockdefs file for the keys, and that mod was never intended to be used with other gameplay mods like brutal doom this old 1993 code is not modular or adaptive mixing stuff together doesnt work on this old game.  So, no there is no way to make them compatible and still play normal doom with it.
