### ISSUE TITLE
Taking Damage from RPG When Back to Wall

### ISSUE THREAD

**Issue by sashokbg** [BLOODWOLF333/Brutal-Doom-Community-Expansion#397]
### Version
Brutal doom wad version: brutalv21.pk3

### Environment
PC, Linux - Manjaro

### Port
GZDoom g4.8.2-m - 2022-07-04 10:31:18 +0200 - SDL version
Compiled on Jul  8 2022

### Description
When using the RPG and firing rockets and standing with my back up to a wall I take damage for some reason.
Problem does not occur when running vanilla gzdoom.

**Comment by Shockwave508** [comment]
Do you have Rocket Launcher Backblast enabled in the Brutal Doom options? If so, there's your problem. Disabling it will nullify this self-damage, as a gameplay modifier.

**Comment by BLOODWOLF333** [comment]
Rocketbackblast is on by default in brutal doom v21 Gold in brutal doom options.  So, thats working as Mark designed it.

**Comment by sashokbg** [comment]
silly me the option did the trick :). Thank you !
