### ISSUE TITLE
Hellknights become invincible when executing marines/players.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#4]
Version: Dev Snapshot v0.0.1
Environment: Mobile (Delta Touch)
Port: LZDoom v3.85
Description: When executing Friendly Marines/Players, Hell Knights are completely immune to all damage while that animation is playing. First observed when attempting to use the SSG in the aforementioned situation; literally saw sparks flying when I shot him. Conversely, Pinkys can already be damaged and/or killed while chowing down on a Zombie or Imp that it just killed amidst infighting.

**Comment by BLOODWOLF333** [comment]
I think I have seen Barons and Revenants display this behavior as well and it is bothersome.
