### ISSUE TITLE
weird skybox in e2m1

### ISSUE THREAD

**Issue by nathanlycan** [BLOODWOLF333/Brutal-Doom-Community-Expansion#400]
skybox has a weird horizontal interruption?

**Comment by BLOODWOLF333** [comment]
![Screenshot_Doom_20221230_165422](https://user-images.githubusercontent.com/16950832/210116646-e18ffb72-aad0-4802-a63e-552cff976699.png)
What?  You have to give way more detail than that dude.  Same sky texture that is used in vanilla Doom, I checked and brutal doom isnt messing with so......what?

**Comment by nathanlycan** [comment]
Sorry for that  if you clip out of bounds the sky box repeats itself
horizontaly. You can see easily if you jump out of the window. Not a big
deal just a minor visual thing. BTW thank you for all your hard work on
polishing up brutal doom. Your version is my favorite.

**Comment by BLOODWOLF333** [comment]
Thanks.

But yes this is normal vanilla Doom behavior where it tiles the sky textures.  Launch just vanilla old doom and you will see the same thing.
