### ISSUE TITLE
Performing fatalities and entering vehicles while rolling

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#401]
This bug always occurs when you perform a fatality while you're still rolling, and when the rolling is finished, you'll see your arms flicker in first person.

And while you're rolling, immediately enter a vehicle or use a mounted gun, when you exit them you'll continue rolling as it hasn't finished yet.

**Comment by BLOODWOLF333** [comment]
The flickering fists when performing a roll and doing a fatality I cannot reproduce with zandronum or GZDoom.  Are you loading another mod with this that changes any weapons and possibly the BrutalWeapon which all the weapons inherit from?

The vehicle + rolling bug I reproduced and will fix now.

**Comment by DuyGamerLHB** [comment]
Ah I see. Here's the flickering fists in case you still can't duplicate it. I just tested it on GZDoom with the latest version and it's also the only mod I loaded Doom with.
[https://youtu.be/UPgaxMIxanM](url)

Btw thanks for fixing the other one, I appreciate it

**Comment by BLOODWOLF333** [comment]
Now the roll animation will finish and then play the fatality animation before disabling the camera.

**Comment by DuyGamerLHB** [comment]
Thank you so much, Wolf. You're the best
