### ISSUE TITLE
3 more bugs and I think that should be all of them

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#403]
1. The first person execution, stomping, only works when the player's falling down from jumping, not right after they jump sometimes, I don't know if this one is intentional
2. Sliding before ending the level, causes the weapon to stay hidden in the next level till you fire it
3. The pickups are a bit delayed visually

**Comment by BLOODWOLF333** [comment]
1. The invisible Use projectile the player fires when you press use has a limited (melee) range so, I don't think anything is wrong here.  And you have to do this jump execution so fast most people don't bother with it.

2. That is EXTREMELY edge-case scenario man....why are you doing that?  There is no way in decorate to account for something like that.
