### ISSUE TITLE
Yet another one (also sorry if I'm bothering you lol)

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#404]
Sometimes when you throw a head at a zombieman's face (or possibly headshot him) while he's standing on water, he just gets erased out of existence when he dies

**Comment by BLOODWOLF333** [comment]
Nah this is a legit bug that has been plaguing various dying or dead actors.  The Archvile used to do this all time so I just have to figure out and remember how I fixed it.
