### ISSUE TITLE
The least noticable gore bug

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#405]
A headless imp still spawns a head when gibbed (possibly the kneeling ones)

**Comment by BLOODWOLF333** [comment]
Provide the exact steps to reproduce so I can identify the problem actor and fix these things quickly

**Comment by BLOODWOLF333** [comment]
Fill out all the required fields in the template when making a bug report next time
