### ISSUE TITLE
A shotgunner who lost his leg

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#406]
When you gib a shotgun guy when he's holding his dismembered leg, it'll cause him to spawn the remains of a zombieman instead. Using an smg to shoot his leg first and a super shotgun can easily duplicate this

**Comment by BLOODWOLF333** [comment]
Why do you refuse to fill out the bug report template?

**Comment by DuyGamerLHB** [comment]
Sorry, I'll fill it out the next time, I promise
