### ISSUE TITLE
Suggestions: Void grenades, Dragon's Breath ammo, alt fire modes, and other stuff.

### ISSUE THREAD

**Issue by mknepper** [BLOODWOLF333/Brutal-Doom-Community-Expansion#419]
So, this is pretty simple. Brutal Doom Platinum has these weapons, grenades, and types of ammunition in it. It also has an alt-mode for the chaingun that shoots nails that bounce all over the area and chop enemies up. Anyway, here's a short list of suggestions:

Weapons:
1. Freeze ray gun
2. Nailgun or alt-mode nail ammo for chaingun
3. Dragonbreath ammo for SSG and shotgun
4. Glass slugs for SSG and shotgun
5. Alt-mode fire for BFG from Brutal Doom Platinum that resembles the original alpha DOOM BFG

Grenades:
1. Void grenades
2. Freeze grenades

Player:
1. Double jump
2. Grabbing ledges as seen in Project Brutality or Brutal Doom Plantinum

Anyway, I know these are not necessarily going to be added and the game is fine without them, just thought I'd suggest it.

**Comment by BLOODWOLF333** [comment]
Thanks for the suggestion but, I will pass.  My intent is to remain close to vanilla-Brutal Doom and not turn this into Platinum or Project Brutality, and ledge grabbing I believe Dox said is done with ZScript which makes it GZdoom specific and is not supported in Zandronum which is the only port I develop for and care about for multiplayer.  All these mods would lose their uniqueness if we all did the same things.
