### ISSUE TITLE
There's an issue with the deathmatch mode

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#421]
**Version:** 21.13.2 (Released 8 hours ago)
Tested on a computer, but I think it happens in all devices
**Port:** Zandronum
**Description:**
I think I know what the guest was saying in the Moddb page, I just tested the Brutal Deathmatch mode and none of the weapons I used, except for the Plasma Rifle and the fists, registered any hit on the bots.
And if I remember correctly, this also happened in the previous version too but I still can't figure out what caused it.

**Comment by BLOODWOLF333** [comment]
It's because I added +MTHRUSPECIES to the hitpuffs so that hitscan attacks will pass through other players and the friendly marines and that also inadvertently also fucks it up for deathmatch, damn it.  I never play DM and forgot to check this so I am fixing it now.
