### ISSUE TITLE
VanillaShotgun guys get stuck on a frame of death animation when gibbed.

### ISSUE THREAD

**Issue by ClevelandRock** [BLOODWOLF333/Brutal-Doom-Community-Expansion#424]
### Version
v21.13.2 Development

### Environment
Windows 10 PC

### Port
GZDoom version g4.11pre-149-gc3d99fa69

### Description
I'm probably about to waste my time on something you already know, but I haven't seen it reported yet…

After a shotgun guy plays his gibbed animation, he plays a second death animation and gets stuck on a frame. To recreate it, just make a shotgun guy explode.

Here's a bunch of shotgun guys frozen in place after getting blown up:
![2023-04-21 03_13_57-UAC Testing Center - Sergeant_Mark_IV's BRUTAL DOOM version 21 13 2](https://user-images.githubusercontent.com/15882664/233567866-4be634b6-8718-489e-8a85-09d86ea0e551.png)

Thanks for all your hard work!

**Comment by DuyGamerLHB** [comment]
It was the vanilla one right?

**Comment by DuyGamerLHB** [comment]
Yep, the S, T, U, V frames were reused as the other animation

**Comment by BLOODWOLF333** [comment]
Yeah I never play with vanilla monsters on and I guess not many other people do either since this hasn't been reported, I would never have caught this.  That is important to mention if you have specific settings on/off since the vanilla monsters are separate monsters from the "brutal" ones.

**Comment by ClevelandRock** [comment]
Yes, they're vanilla monsters. I completely forgot. Sorry.
