### ISSUE TITLE
Start Error: Sounds that are reserved for players cannot be reassigned

### ISSUE THREAD

**Issue by Skibicki** [BLOODWOLF333/Brutal-Doom-Community-Expansion#437]
### Version
21.14.0 or commit [42729f9](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/commit/42729f9286aa4d0df0de90042e69722f05a191f7)
### Environment
Desktop

### Port
GZdoom, LZDoom, and Zandronum

### Description
The game is prevented from starting. The message below is shown.
Sounds that are reserved for players cannot be reassigned

Load Order:
Brutal Doom
VietDoom Weapons
VietDoom WSS
https://www.moddb.com/addons/vietdoom-weapons

**Comment by rautamiekka** [comment]
'latest' ain't a valid version number, or in the case of an open code, the commit string.

**Comment by BLOODWOLF333** [comment]
Remove the vietdoom mods and retry

**Comment by BLOODWOLF333** [comment]
Ok I tried this out myself, these addons have so many start-up errors and duplicate images where Slade won't even save the pk3 this is not a problem with my mod and I am not conforming my stuff to work with these addons.  Report the issue to the addon-author the problem is their stuff not mine.
