### ISSUE TITLE
Map as mini-map and minor translation issues

### ISSUE THREAD

**Issue by kam92** [BLOODWOLF333/Brutal-Doom-Community-Expansion#438]
### Description
Hello, I would like to contribute to the project. I've been playing for ages and I want to try to implement my ideas. Are there any guides / suggested guidelines to follow? I'm sorry to write this in the issue section but i haven't found a forum/discord, etc. 

My initial ideas:
-Fix Portuguese translation (a lot of stuff still in English in the options screen, i could translate all in 5 minutes).
-Fix the font when there is accents, they show in red but shouldn't:
![image](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/79944246/0496a5ca-6536-4700-99e6-9d8ea7c28b20)

I also want to make an option where you press tab, but instead of the map appearing in the center, it will appear in the upper-right corner, like a mini-map (i think upper-right is where most FPS games place it now days but that can be customized by user).

Thanks in advance.

**Comment by BLOODWOLF333** [comment]
Sure, only guidelines I could offer is to just document the changes briefly in the expansionchangelog.txt and thats it really

**Comment by BLOODWOLF333** [comment]
Closing as there is no progress
