### ISSUE TITLE
Do Away With Fake Pickup Sprites

### ISSUE THREAD

**Issue by BLOODWOLF333** [BLOODWOLF333/Brutal-Doom-Community-Expansion#439]
### To Do List
Do away with the fake sprites for weapons and ammo pickups

**Comment by BLOODWOLF333** [comment]
There is no way to replace the on-map weapon pickups with a spawner that would drop one weapon for the brutal player and one weapon for the purist player without the player picking up both weapons so, screw it

**Comment by JMartinez9820** [comment]
@BLOODWOLF333 You could use ForbiddenTo and RestrictedTo on Weapons for purist along with a custominventory item, i know you probably scrapped this but do you mind if I experiment something with that? I know sometimes you have to check for the player number too.

**Comment by BLOODWOLF333** [comment]
> @BLOODWOLF333 You could use ForbiddenTo and RestrictedTo on Weapons (both are compatible with Zandronum) for purist along with a custominventory item, i know you probably scrapped this but do you mind if I experiment something with that? I know sometimes you have to check for the player number too.

Sure go ahead, I have kind of given up because my idea doesnt work for weapons.  I can make spawners that drop an ammotype for each playerclass and that works but doing the same thing for weapons does not.  They dont seem to obey the Inventory.ForbiddenTo and the player will pickup the wrong playerclass weapons (specifically when trying to insert brutal doom into Heretic with a brutaldoom player class, vanilla/purist class, and a corvus class.  The doom players will keep picking up heretic weapons when they shouldnt)
[DoominHeretic.zip](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/files/13763020/DoominHeretic.zip)

**Comment by JMartinez9820** [comment]
Also what is that DoominHeretic thing? Is it a patch? If so, I can check as well for that. You want Zandro compatibility with the DoominHeretic thing too right?

**Comment by BLOODWOLF333** [comment]
Its just an example pk3 of what I was working on without all of the brutal doom stuff to show the problem with the weapon pickups not working like how ammo does.
