### ISSUE TITLE
Friendly rescued marines gets stuck attacking blood tank in e2m4

### ISSUE THREAD

**Issue by knowsshit** [BLOODWOLF333/Brutal-Doom-Community-Expansion#440]
### Version
brutalv21.13.2.pk3

### Environment
PC, Windows 11

### Port
GZDoom g4.11.1

### Description
In Ultimate Doom map e2m4 there are some blood tanks with bloody skeleton monsters popping out of some of them. Both my friendly (rescued) marines got stuck attacking one of the tanks. Attaching screenshot of this happening, as well as a screenshot of the map showing where.

![Screenshot_Doom_20231211_210423](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/93446682/b579cb7c-1a67-4c55-9152-bfe25ef160cc)
![Screenshot_Doom_20231211_210431](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/93446682/76645d1e-896c-45dd-95e4-18e38999ccbd)

**Comment by BLOODWOLF333** [comment]
Try it with 21.14.1 you are using a really old version dude

**Comment by knowsshit** [comment]
I just checked with 21.14.1 and the same happened. The marine just stands there and blasts away at a blood tank where this bloody skeleton monster escaped from.

I didn't see it being fixed in the changelog, so I reported it even though I was on an older version. 

There's a marine to be rescued to the right in the blood floor area and the red tanks are straight up ahead so it is easy to check. 

![Screenshot_Doom_20231212_215058](https://github.com/BLOODWOLF333/Brutal-Doom-Community-Expansion/assets/93446682/0f505df8-638f-48a4-9351-b2fa4968f14a)

PS: I also noticed that some marines have the super shotgun while playing Doom 1 levels. I guess they can have all kinds of weapons, but it seemed a bit odd since one of them died and I got the SSG from the dead marine and it seemed out of place for Doom 1 levels.

PPS: Thank you for the fast reply and all the awesome work!

**Comment by BLOODWOLF333** [comment]
I was able to duplicate the issue today, this bug was another issue caused by jump states in actors jumping to a death state but not actually killing the monster (its still has hitpoints and is alive even though the code told it to jump to a death state but, that doesnt actually kill it) so this is fixed, good catch!
