### ISSUE TITLE
Chainsaw's pickup sprite

### ISSUE THREAD

**Issue by DuyGamerLHB** [BLOODWOLF333/Brutal-Doom-Community-Expansion#445]
### Description
Now I just noticed that the chainsaw's pickup sprite doesn't quite match when BD is loaded with a different wad since it uses the default sprite, I don't know if it should have one of its own or just simply leave it be

**Comment by BLOODWOLF333** [comment]
Like Deus Vult II where the saw is replaced by the Heretic Gauntlets?  I'm not really bothered by it but if you think the vanilla Doom CSAWA sprite should be included then that would be okay too.

**Comment by DuyGamerLHB** [comment]
> Like Deus Vult II where the saw is replaced by the Heretic Gauntlets? I'm not really bothered by it but if you think the vanilla Doom CSAWA sprite should be included then that would be okay too.

Yep, and replaced by the original ankle grinder in FreeDoom

**Comment by BLOODWOLF333** [comment]
Closed by #446
