### ISSUE TITLE
Odd reloading issues affecting almost every weapon.

### ISSUE THREAD

**Issue by ShadowMosesIsland** [BLOODWOLF333/Brutal-Doom-Community-Expansion#452]
### Version
Observed in both stable v21.15.0 and the latest snapshot.

### Environment
Computer

### Port
GZDoom and Zandronum

### Description
With reloading enabled, weapons sometimes don't reload when pressing the reload key, despite having enough ammo. It seems to affect almost **every** weapon with reloading ability. The bug also seems to be different for each weapon, and dependent on the time between shooting with the weapon and attempting to reload.

Here are some observed behaviors you can try to replicate, preceded by loading any map, obtaining the mentioned weapon, and switching to it. Steps to replicate the bug may or may not work for on the first try.

**Shotgun**:

Behavior 1: 
1. shoot
2. wait 3 seconds or more
3. press reload once, can't reload
4. press reload again, can't reload

Behavior 2: 
1. shoot
2. spam reload key immediately, may or may not reload

Behavior 3: 
1. shoot
2. wait 3 seconds or more, can't reload
3. zoom in
4. press reload, it doesn't reload
5. press reload again, it reloads

**Revolver**:

Behavior 1: 
1. shoot
2. press reload once, it reloads
3. shoot again
4. press reload once, it doesn't reload
5. press reload once again, it reloads 

**Auto Shotgun**:

Behavior 1: 
1. hold attack button for around half a second to fire a few shots
2. wait 3 seconds or more
3. press reload once, it does not reload
4. wait 2 seconds
5. press reload again, it does not reload
6. wait 2 seconds
7. press reload again, it reloads

### Additional info
This bug does not seem to occur in the original Brutal Doom v21 mod by Sgt Mark IV.

**Comment by BLOODWOLF333** [comment]
which reload keybind do you have defined?  The sourceport reload or the BD reload key?  The wife and I playtest this every night on my servers and reloading works fine

**Comment by ShadowMosesIsland** [comment]
That might be the issue, I'll check it when I'll get home.

**Comment by ShadowMosesIsland** [comment]
Yes it was indeed the issue, have just seen your commit removing the BD keybind.
