### ISSUE TITLE
Tactical class has fast movement speed with capslock on when not sprinting

### ISSUE THREAD

**Issue by ShadowMosesIsland** [BLOODWOLF333/Brutal-Doom-Community-Expansion#453]
### Description
Strafing left and right is faster than moving forward, especially noticeable when playing Tactical class. For me, it makes movement feel very odd, and straferunning very annoying. It can make dodging easier, I guess? But there is a feature that can be used for that, it's called rolling left and right.

I assume this is intentional and not a bug, so I'm asking for adding an option to change it back to the way it was in the original Brutal Doom. I hope it's not too much of a headache to implement.

EDIT: Hmm, it seems to only affect the Tactical class, my bad.

**Comment by ShadowMosesIsland** [comment]
Oh sorry if I wasn't clear, but the speed itself is not a problem, but rather the forward-strafe speed ratio when moving without sprint. It feels unintuitive to move faster strafing than moving forward, I can probably get used to it, but I'd still prefer the old movement. Perhaps it could be turned into a server cvar, that decides whether this new or legacy (v21) movement will be used. I'll try to do that myself today.

**Comment by BLOODWOLF333** [comment]
Thats vanilla Doom behavior, its trigonometry https://doom.fandom.com/wiki/Straferunning.  I didnt change anything about that

**Comment by ShadowMosesIsland** [comment]
Ah, it seems like I still wasn't clear, but I can understand why 😅 The straferunning is not a problem at all, it's part of the DOOM, I know.

My point is, when you play as tactical class, moving LEFT or RIGHT is much faster than moving FORWARD. No sprint involved or pressing two movement keys at the same time, the issue affects them, but they're not the cause. I can make a video to show exactly what I mean.

**Comment by ShadowMosesIsland** [comment]
https://youtu.be/SFX6rijoFx0

I have just noticed that it's happening if you have cl_run (toggle run) on. This can be easily fixed by adding `Player.SideMove 1, 0.5 ` property to TacticalDoomer class.
