### ISSUE TITLE
Unloading a weapon when reserves are full will waste ammo.

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#6]
Version: Dev Snapshot v0.0.1
Environment: Mobile (Delta Touch)
Port: LZDoom v3.85
Description: When reserve ammunition for a given weapon is at absolute maximum, unloading such a weapon for any reason will irrevocably waste however many rounds were in the current magazine.

**Comment by BLOODWOLF333** [comment]
This is on the player to not waste their ammo unloading when full, doesnt need to be made more complicated.
