### ISSUE TITLE
Sourceport crosshair stays when aiming down sights of Shotgun/Assault Shotgun/Rocket Launcher/Railgun

### ISSUE THREAD

**Issue by Zodomaniac** [BLOODWOLF333/Brutal-Doom-Community-Expansion#7]
### Version
Dev snapshot 0.0.1

### Environment
Windows 10 x64 PC

### Port
GZDoom 4.3.3

### Description
Just aim down sights with the aforementioned weapons.

I've got fixes, please add me as a contributor and I will submit a pull request.

**Comment by BLOODWOLF333** [comment]
I added in all the A_SetCrosshair(0) and (41) last night to the zoomed and unzoomed ready states (because reloading while zoomed will cause the crosshair to stay off when it goes back to unzoomed ready) but, maybe that should be done a different way.
