### ISSUE TITLE
Multiple issues with Meatshields

### ISSUE THREAD

**Issue by Shockwave508** [BLOODWOLF333/Brutal-Doom-Community-Expansion#94]
### Version
Dev Snapshot v0.2.1

### Environment
Mobile (Delta Touch)

### Port
LZDoom v3.86a

### Description
Issue 1: When holding any kind of meatshield, your pistol's bullets will actually be blocked, instead doing mild damage to your own meatshield.

Issue 2: Throwing your meatshield after expending your 16 bullets (throw with Primary Fire) will cause a VM Abort once your former shield hits something.

**Comment by BLOODWOLF333** [comment]
Cant duplicate the VM abort on desktop
